#!/usr/bin/env python3
"""self-heal.py — daily deterministic self-heal + compliance metering.

Two layers, complementing the LLM `system-audit.sh` (which is semantic + report-only):

  LAYER A — mechanical heal: cheap deterministic plumbing checks. AUTO-FIX only the
    safe, idempotent, reversible class (broken symlinks, non-exec hooks); everything
    judgment-laden (config drift that could regress newer live state, stray .git
    dirs) is REPORTED, never blind-applied (feedback_validate_heal_commands).

  LAYER B — compliance meters: a pluggable registry that *counts adherence* to
    standards that have a measurable signal, and alerts below threshold. This is the
    generalizable answer to "catch stuff like the 2% sign-off gap more broadly":
    a standard isn't trusted because it exists, it's trusted because a meter measures
    it. Adding a meter is one function appended to METERS.

Output: a JSON result to stdout (the .sh wrapper renders markdown + Discord digest).
Portable: derives repo root from this file; no hardcoded per-machine paths.

Run modes:
  --dry-run   report what WOULD heal, change nothing (default for tests)
  --apply     perform the safe auto-heals (default for the scheduled run)
  --json      emit machine-readable JSON only (no human summary on stderr)
"""
import argparse, json, os, re, subprocess, sys, glob, datetime, time

REPO = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))
HOME = os.path.expanduser("~")
GATE_LOG = os.path.join(HOME, ".openclaw", "logs", "signoff-gate.jsonl")
# Repo-tracked registry of bug-derived command checks (added via add-healthcheck.py).
# Each fix that's mechanically detectable registers one entry here, so the harness
# grows itself — no python editing, and it syncs to every machine.
HEALTH_CHECKS_FILE = os.path.join(REPO, "docs", "process", "state", "health-checks.json")
# Machine-local runtime state (each machine self-heals its own plumbing) — NOT in the
# repo, to avoid cross-machine churn/conflicts. Regenerated by every self-heal run.
WORKLIST = os.path.join(HOME, ".openclaw", "self-heal-worklist.json")

OK, HEALED, NEEDS_HUMAN = "OK", "HEALED", "NEEDS_HUMAN"
PASS, ALERT = "PASS", "ALERT"

# Escalation tiers (per agent-escalation-thresholds.md):
#   auto  → fixed silently, no human, no record beyond the report
#   agent → a session must act, but it is NOT an Ant decision → self-heal worklist
#           (consumed by the next <<MACHINE_1_ID>> session; never pinged to Ant)
#   ant   → trips the escalation bar (money / irreversible-high-cost / external /
#           secrets / destructive-ambiguous) → @Ant decide-and-present ping
AUTO, AGENT, ANT = "auto", "agent", "ant"

# Per-finding tier. Default for a needs-action finding is AGENT — Ant is pinged ONLY
# when a check explicitly returns escalation=ANT (none do today; the tier is reserved
# for findings that genuinely match the bar, e.g. a future leaked-secret meter).
DEFAULT_TIER = AGENT

LANE_TMUX_SESSIONS = {
    "hub",
    "g1-workforce",
    "g2-dashboard",
    "g3-example",
    "g4-trading",
    "g5-brand",
    "g6-life",
}
TMUX_ACTIVE_MARKERS = (
    "press esc to interrupt",
    "esc to interrupt",
    "ctrl+c to interrupt",
    "running…",
    "running...",
    "thinking…",
    "thinking...",
    "tool_use",
)


def sh(cmd, timeout=60):
    # METIS_PYTHON pins children to the interpreter running this harness. Needed
    # because command-checks run under `bash -lc`, whose /etc/profile rebuilds
    # PATH (Ant's real PATH lives in zsh files bash never sources) and resolves
    # python3 to a yaml-less /usr/local/bin install — the taxonomy meter died
    # under it (found 2026-06-11). An env var survives profile sourcing; PATH
    # does not.
    env = dict(os.environ, METIS_PYTHON=sys.executable)
    try:
        p = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=timeout, env=env)
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    except Exception as e:
        return 1, str(e)


def _tmux_reaper_threshold_s() -> int:
    raw = os.environ.get("METIS_TMUX_REAPER_MAX_AGE_HOURS", "48")
    try:
        hours = float(raw)
    except ValueError:
        hours = 48.0
    return max(1, int(hours * 3600))


def _tmux_mock_sessions():
    """Optional test hook. Shape:
    {"sessions":[{"name":"claude-1","attached":false,"last_activity":0,"pane":"..."}]}"""
    path = os.environ.get("METIS_TMUX_REAPER_MOCK")
    if not path:
        return None
    data = json.load(open(path))
    out = []
    for row in data.get("sessions", []):
        name = str(row.get("name", ""))
        out.append({
            "name": name,
            "attached": bool(row.get("attached", False)),
            "last_activity": int(row.get("last_activity", 0) or 0),
            "pane": str(row.get("pane", "")),
        })
    return out


def _tmux_live_sessions():
    rc, out = sh(["bash", "-lc", "tmux list-sessions -F '#{session_name}|#{session_attached}|#{session_activity}' 2>/dev/null"])
    if rc != 0:
        return []
    sessions = []
    for line in out.splitlines():
        parts = line.split("|", 2)
        if len(parts) != 3:
            continue
        name, attached, activity = parts
        pane = ""
        # Capture a bounded tail from the first pane in the session. Fail closed:
        # if we cannot inspect it, treat it as active and skip reaping.
        prc, pout = sh(["bash", "-lc", f"tmux capture-pane -p -S -80 -t ={name}: 2>/dev/null"], timeout=10)
        if prc != 0:
            pane = "press esc to interrupt"
        else:
            pane = pout[-12000:]
        try:
            last_activity = int(activity)
        except ValueError:
            last_activity = int(time.time())
        sessions.append({
            "name": name,
            "attached": attached == "1",
            "last_activity": last_activity,
            "pane": pane,
        })
    return sessions


def _tmux_reap_plan(sessions, now=None, threshold_s=None):
    now = int(time.time() if now is None else now)
    threshold_s = _tmux_reaper_threshold_s() if threshold_s is None else threshold_s
    plan = []
    for s in sessions:
        name = s.get("name", "")
        pane = (s.get("pane") or "").lower()
        last_activity = int(s.get("last_activity") or 0)
        age_s = max(0, now - last_activity)
        reason = None
        reap = False
        if not re.match(r"^claude-[0-9]+$", name):
            reason = "protected: not a numbered claude session"
        elif name in LANE_TMUX_SESSIONS or name == "ccc":
            reason = "protected: lane/mobile session"
        elif s.get("attached"):
            reason = "protected: attached"
        elif any(marker in pane for marker in TMUX_ACTIVE_MARKERS):
            reason = "protected: active pane marker"
        elif age_s < threshold_s:
            reason = f"protected: age {age_s}s below threshold {threshold_s}s"
        else:
            reap = True
            reason = f"detached idle {age_s}s >= threshold {threshold_s}s"
        plan.append({**s, "age_s": age_s, "reap": reap, "reason": reason})
    return plan


# ───────────────────────── LAYER A — mechanical heal ─────────────────────────

def heal_symlinks(apply):
    """Re-link any ~/.claude symlink declared in mirror-manifest.json that is
    broken/missing/wrong. Pure plumbing, fully reversible → safe to auto-heal."""
    manifest = os.path.join(REPO, "ClaudeCode", "mirror-manifest.json")
    actions, bad = [], 0
    try:
        m = json.load(open(manifest))
    except Exception as e:
        return {"name": "symlinks", "status": NEEDS_HUMAN,
                "detail": f"cannot read mirror-manifest.json: {e}", "actions": []}
    for entry in m.get("symlinks", []):
        link = os.path.expanduser(entry["link"])
        want = os.path.join(REPO, entry["target"])
        cur = os.path.realpath(link) if os.path.lexists(link) else None
        if cur == os.path.realpath(want):
            continue
        bad += 1
        if apply:
            try:
                if os.path.lexists(link):
                    os.remove(link)
                os.makedirs(os.path.dirname(link), exist_ok=True)
                os.symlink(want, link)
                actions.append(f"relinked {entry['link']} → {entry['target']}")
            except Exception as e:
                actions.append(f"FAILED relink {entry['link']}: {e}")
        else:
            actions.append(f"would relink {entry['link']} → {entry['target']}")
    if bad == 0:
        return {"name": "symlinks", "status": OK, "detail": "all manifest symlinks intact", "actions": []}
    status = HEALED if apply and all("FAILED" not in a for a in actions) else NEEDS_HUMAN
    return {"name": "symlinks", "status": status, "detail": f"{bad} symlink(s) off", "actions": actions}


def heal_hook_exec(apply):
    """Ensure every hook/bin script is executable. Lost +x silently disables a hook."""
    actions = []
    for pat in ("ClaudeCode/hooks/*.sh", "ClaudeCode/bin/*.sh", "scripts/*.sh"):
        for f in glob.glob(os.path.join(REPO, pat)):
            if not os.access(f, os.X_OK):
                rel = os.path.relpath(f, REPO)
                if apply:
                    try:
                        os.chmod(f, os.stat(f).st_mode | 0o111)
                        actions.append(f"chmod +x {rel}")
                    except Exception as e:
                        actions.append(f"FAILED chmod {rel}: {e}")
                else:
                    actions.append(f"would chmod +x {rel}")
    if not actions:
        return {"name": "hook-exec", "status": OK, "detail": "all scripts executable", "actions": []}
    status = HEALED if apply and all("FAILED" not in a for a in actions) else NEEDS_HUMAN
    return {"name": "hook-exec", "status": status, "detail": f"{len(actions)} non-exec script(s)", "actions": actions}


def check_hook_wiring(apply):
    """Verify every ClaudeCode/hooks/*.sh referenced from settings.json is actually
    wired. REPORT only — editing settings.json is a judgment call (localKeys merge)."""
    settings = os.path.join(HOME, ".claude", "settings.json")
    try:
        blob = open(settings).read()
    except Exception as e:
        return {"name": "hook-wiring", "status": NEEDS_HUMAN, "detail": f"no settings.json: {e}", "actions": []}
    # Hooks that MUST be wired (the enforcement/identity set).
    required = ["hook-signoff-gate.sh", "hook-alerts.sh", "hook-session-init.sh",
                "hook-prompt-guard.sh"]
    missing = [h for h in required if h not in blob]
    if not missing:
        return {"name": "hook-wiring", "status": OK, "detail": "required hooks wired", "actions": []}
    return {"name": "hook-wiring", "status": NEEDS_HUMAN,
            "detail": f"settings.json missing: {', '.join(missing)}",
            "actions": [f"add {h} to the matching hooks array in ~/.claude/settings.json" for h in missing]}


def check_mirror_drift(apply):
    """Config drift <<MACHINE_1_ID>>-vs-canonical. REPORT only — mirror apply is canonical→live and
    can regress newer live state (feedback_validate_heal_commands)."""
    rc, out = sh(["python3", os.path.join(REPO, "scripts", "mirror.py"), "check"])
    clean = (rc == 0 and "in sync" in out.lower())
    if clean:
        return {"name": "mirror-drift", "status": OK, "detail": "<<MACHINE_1_ID>> in sync with canonical", "actions": []}
    return {"name": "mirror-drift", "status": NEEDS_HUMAN, "detail": "mirror drift detected",
            "actions": ["review: python3 scripts/mirror.py check  (apply only after confirming live isn't newer)"]}


def check_stray_git(apply):
    """Nested .git dirs under projects/ cause wrong-dir writes / silent git failures —
    but ONLY when the outer repo doesn't ignore them. A gitignored nested repo (e.g.
    projects/polymarket-bot, a deliberate public/private carveout with its own remotes)
    is intentional and invisible to outer-repo git ops, so it's NOT a stray. Flag only
    nested .git dirs the outer repo does NOT ignore."""
    rc, out = sh(["bash", "-lc", f"find '{REPO}/projects' -name .git -maxdepth 3 2>/dev/null"])
    strays = []
    for line in out.splitlines():
        d = line.strip()
        if not d:
            continue
        rel = os.path.relpath(d, REPO)
        # outer repo ignores it → deliberate separate repo, not a stray
        ig, _ = sh(["bash", "-lc", f"git -C '{REPO}' check-ignore -q '{rel}'"])
        if ig != 0:
            strays.append(rel)
    if not strays:
        return {"name": "stray-git", "status": OK, "detail": "no un-ignored nested .git under projects/", "actions": []}
    return {"name": "stray-git", "status": NEEDS_HUMAN,
            "detail": f"{len(strays)} un-ignored nested .git dir(s)",
            "actions": [f"investigate {r} — gitignore it (if intentional) or register as submodule" for r in strays]}


def check_gitsync_drift(apply):
    """Live git-sync script vs canonical + heartbeat (the 2026-05-30 corruption class).
    Script/heartbeat drift stays detection-only — which side is canonical is a
    judgment call.  Orphaned daemon stashes are different: the reconciler archives
    risky content before dropping, so daily --apply can clear that mechanical class
    before it accumulates into another sync wedge."""
    rc, out = sh(["bash", os.path.join(REPO, "scripts", "check-sync-drift.sh")])
    if rc == 0:
        return {"name": "gitsync-drift", "status": OK, "detail": "live git-sync matches canonical + healthy", "actions": []}
    if apply and "STASH:" in out:
        r2, o2 = sh([sys.executable, os.path.join(REPO, "scripts", "reconcile-daemon-stashes.py"), "--apply"], timeout=180)
        rc3, out3 = sh(["bash", os.path.join(REPO, "scripts", "check-sync-drift.sh")])
        if r2 == 0 and rc3 == 0:
            actions = [l.strip() for l in o2.splitlines() if "archived " in l or "dropped " in l or "wrote inventory" in l]
            return {"name": "gitsync-drift", "status": HEALED,
                    "detail": "auto-reconciled orphaned daemon stashes; git-sync healthy",
                    "actions": actions[:6] or ["ran reconcile-daemon-stashes.py --apply"]}
        lines = [l.strip() for l in (o2 + "\n" + out3).splitlines() if l.strip()]
        return {"name": "gitsync-drift", "status": NEEDS_HUMAN,
                "detail": "daemon stash auto-reconcile failed",
                "actions": lines[-5:] or ["run scripts/reconcile-daemon-stashes.py manually"]}
    lines = [l.strip() for l in out.splitlines() if l.strip() and not l.startswith("OK")]
    return {"name": "gitsync-drift", "status": NEEDS_HUMAN,
            "detail": "git-sync script drift or stale heartbeat",
            "actions": lines[:4] or ["run scripts/check-sync-drift.sh and review"]}


def heal_autosync(apply):
    """Auto-sync daemon liveness (#101 — daemon found fully UNLOADED, deferred commits
    stranded). Read-only in dry-run; in apply mode delegates the reload to the proven
    ensure-autosync-loaded.sh (which self-alerts on failure)."""
    label = "ant.openclaw-git-sync"
    plist = os.path.join(HOME, "Library", "LaunchAgents", f"{label}.plist")
    rc, out = sh(["bash", "-lc", f"launchctl list 2>/dev/null | grep -q {label}"])
    loaded = (rc == 0)
    if loaded:
        return {"name": "autosync-daemon", "status": OK, "detail": "daemon loaded", "actions": []}
    if not os.path.exists(plist):
        return {"name": "autosync-daemon", "status": OK, "detail": "daemon not installed on this machine", "actions": []}
    if apply:
        r2, o2 = sh(["bash", os.path.join(REPO, "scripts", "ensure-autosync-loaded.sh")])
        if "reload FAILED" in o2 or "RELOAD FAILED" in o2:
            return {"name": "autosync-daemon", "status": NEEDS_HUMAN, "detail": "daemon unloaded; reload FAILED",
                    "actions": [f"reload manually: launchctl load -w {plist}"]}
        return {"name": "autosync-daemon", "status": HEALED, "detail": "daemon was unloaded — reloaded", "actions": ["reloaded ant.openclaw-git-sync"]}
    return {"name": "autosync-daemon", "status": NEEDS_HUMAN, "detail": "daemon UNLOADED (deferred commits will strand)",
            "actions": [f"reload: launchctl load -w {plist}"]}


def heal_poller(apply):
    """Notion run-poller liveness — the ONLY autonomous channel that runs registry
    keys from a Command Center card. Found silent 4h+ on 2026-06-17 with no recovery.
    Mirrors heal_autosync: read-only in dry-run; in apply mode delegates the reload
    to ensure-poller-loaded.sh (which self-alerts on failure)."""
    label = "ant.notion-run-poller"
    plist = os.path.join(HOME, "Library", "LaunchAgents", f"{label}.plist")
    rc, _ = sh(["bash", "-lc", f"launchctl list 2>/dev/null | grep -q {label}"])
    loaded = (rc == 0)
    if loaded:
        return {"name": "notion-run-poller", "status": OK, "detail": "poller loaded", "actions": []}
    if not os.path.exists(plist):
        return {"name": "notion-run-poller", "status": OK, "detail": "poller not installed on this machine", "actions": []}
    if apply:
        _, o2 = sh(["bash", os.path.join(REPO, "scripts", "ensure-poller-loaded.sh")])
        if "reload FAILED" in o2 or "RELOAD FAILED" in o2:
            return {"name": "notion-run-poller", "status": NEEDS_HUMAN, "detail": "poller unloaded; reload FAILED",
                    "actions": [f"reload manually: launchctl load -w {plist}"]}
        return {"name": "notion-run-poller", "status": HEALED, "detail": "poller was unloaded — reloaded", "actions": ["reloaded ant.notion-run-poller"]}
    return {"name": "notion-run-poller", "status": NEEDS_HUMAN, "detail": "poller UNLOADED (run-on-<<MACHINE_1_ID>> relay dead)",
            "actions": [f"reload: launchctl load -w {plist}"]}


def heal_relay_poller(apply):
    """Git-relay poller liveness (#444) — its OWN meter, because heal_poller/heartbeat
    only fire the reload guard when the *Notion* poller drops. <<MACHINE_1_ID>> runs
    ant.relay-poller (cloud→<<MACHINE_1_ID>> requests); <<MACHINE_2_ID>> runs <<MACHINE_2_USER>>.relay-poller (the
    dark-<<MACHINE_1_ID>> FAILOVER half, whose entire value is surviving a down <<MACHINE_1_ID>>, so it
    must self-heal independently). Machine-aware: guards whichever relay plist is
    installed here. Delegates the reload to the (machine-aware) ensure-poller-loaded.sh."""
    label = next((l for l in ("ant.relay-poller", "<<MACHINE_2_USER>>.relay-poller")
                  if os.path.exists(os.path.join(HOME, "Library", "LaunchAgents", f"{l}.plist"))), None)
    if label is None:
        return {"name": "relay-poller", "status": OK, "detail": "relay poller not installed on this machine", "actions": []}
    plist = os.path.join(HOME, "Library", "LaunchAgents", f"{label}.plist")
    loaded = lambda: sh(["bash", "-lc", f"launchctl list 2>/dev/null | grep -q {label}"])[0] == 0
    if loaded():
        return {"name": "relay-poller", "status": OK, "detail": f"{label} loaded", "actions": []}
    if apply:
        _, o2 = sh(["bash", os.path.join(REPO, "scripts", "ensure-poller-loaded.sh")])
        if not loaded() or "reload FAILED" in o2 or "RELOAD FAILED" in o2:
            return {"name": "relay-poller", "status": NEEDS_HUMAN, "detail": f"{label} unloaded; reload FAILED",
                    "actions": [f"reload manually: launchctl load -w {plist}"]}
        return {"name": "relay-poller", "status": HEALED, "detail": f"{label} was unloaded — reloaded", "actions": [f"reloaded {label}"]}
    return {"name": "relay-poller", "status": NEEDS_HUMAN, "detail": f"{label} UNLOADED (#444 git relay dead)",
            "actions": [f"reload: launchctl load -w {plist}"]}


def heal_tag_intake(apply):
    """#438 tag-to-task intake agent liveness. Mirrors heal_poller: the lane only
    runs if its LaunchAgent is loaded, so this is the zero-touch relay that brings
    it live (and re-loads it if it ever drops) on <<MACHINE_1_ID>>'s session-init pass —
    no Command Center card needed. In apply mode delegates to the idempotent
    load-tag-intake-agent.sh (which self-alerts on failure)."""
    label = "ant.notion-tag-intake"
    plist = os.path.join(HOME, "Library", "LaunchAgents", f"{label}.plist")
    # launchctl is the macOS/<<MACHINE_1_ID>> signal; absent on Linux cloud containers → not applicable.
    if sh(["bash", "-lc", "command -v launchctl >/dev/null 2>&1"])[0] != 0:
        return {"name": "notion-tag-intake", "status": OK, "detail": "not a launchd host (lane runs on <<MACHINE_1_ID>> only)", "actions": []}
    rc, _ = sh(["bash", "-lc", f"launchctl list 2>/dev/null | grep -q {label}"])
    if rc == 0:
        return {"name": "notion-tag-intake", "status": OK, "detail": "tag-intake agent loaded", "actions": []}
    if apply:
        _, o2 = sh(["bash", os.path.join(REPO, "scripts", "load-tag-intake-agent.sh")])
        if "load FAILED" in o2:
            return {"name": "notion-tag-intake", "status": NEEDS_HUMAN, "detail": "tag-intake unloaded; load FAILED",
                    "actions": [f"load manually: launchctl load -w {plist}"]}
        return {"name": "notion-tag-intake", "status": HEALED, "detail": "tag-intake was unloaded — loaded", "actions": ["loaded ant.notion-tag-intake"]}
    return {"name": "notion-tag-intake", "status": NEEDS_HUMAN, "detail": "tag-intake UNLOADED (#438 lane not live)",
            "actions": [f"load: bash {os.path.join(REPO, 'scripts', 'load-tag-intake-agent.sh')}"]}


def check_lane_bloat(apply):
    """Lane sessions over the 20k-token bloat line → cold-start cascade. Detection only;
    a reset can clobber an in-flight lane call, so it's agent-tier, not auto."""
    bloated = []
    for lane in ("smith", "scout", "warden", "scribe", "arbiter"):
        p = os.path.join(HOME, ".openclaw", "agents", lane, "sessions", "sessions.json")
        if not os.path.exists(p):
            continue
        try:
            d = json.load(open(p))
            tok = int(d.get(f"agent:{lane}:main", {}).get("inputTokens") or 0)
            if tok > 20_000:
                bloated.append(f"{lane}:{tok:,}")
        except Exception:
            pass
    if not bloated:
        return {"name": "lane-bloat", "status": OK, "detail": "no lane over 20k tokens", "actions": []}
    return {"name": "lane-bloat", "status": NEEDS_HUMAN, "detail": "bloated lane(s): " + ", ".join(bloated),
            "actions": ["run: lane-health --reset-bloated"]}


def heal_stale_tmux_sessions(apply):
    """Reap detached numbered claude-<N> tmux sessions that have been idle longer
    than METIS_TMUX_REAPER_MAX_AGE_HOURS (default 48h).

    Conservative by design: never touch campaign lanes (hub/g1..g6), ccc, attached
    sessions, non-numbered sessions, or panes with active-turn markers. The dry-run
    actions become the self-heal report; --apply performs the same plan and logs
    every kill in that report.
    """
    sessions = _tmux_mock_sessions()
    if sessions is None:
        sessions = _tmux_live_sessions()
    threshold_s = _tmux_reaper_threshold_s()
    plan = _tmux_reap_plan(sessions, threshold_s=threshold_s)
    victims = [p for p in plan if p["reap"]]
    if not victims:
        return {"name": "tmux-stale-reaper", "status": OK,
                "detail": f"no detached claude-<N> sessions idle >= {threshold_s}s",
                "actions": []}
    actions = []
    failed = False
    for v in victims:
        name = v["name"]
        if apply:
            if os.environ.get("METIS_TMUX_REAPER_MOCK"):
                rc, out = 0, ""
            else:
                rc, out = sh(["tmux", "kill-session", "-t", f"={name}"], timeout=10)
            if rc == 0:
                actions.append(f"killed stale tmux session {name}: {v['reason']}")
            else:
                failed = True
                actions.append(f"FAILED kill {name}: {out.strip()[:160]}")
        else:
            actions.append(f"would kill stale tmux session {name}: {v['reason']}")
    return {"name": "tmux-stale-reaper",
            "status": HEALED if apply and not failed else NEEDS_HUMAN,
            "detail": f"{len(victims)} stale detached claude-<N> session(s)",
            "actions": actions}


_RECON = {}
def _reconcile_lines():
    if "lines" not in _RECON:
        rc, out = sh(["python3", os.path.join(REPO, "scripts", "agent-work.py"), "reconcile"])
        _RECON["lines"] = [l.strip() for l in out.splitlines() if re.match(r"(WARN|FAIL)\s+I\d", l.strip())]
    return _RECON["lines"]


def _invariant_finding(name, codes, label):
    pat = re.compile(r"\bI(" + "|".join(str(c) for c in codes) + r")\b")
    hits = [l for l in _reconcile_lines() if pat.search(l)]
    if not hits:
        return {"name": name, "status": OK, "detail": f"no {label} invariant violations", "actions": []}
    fails = [h for h in hits if h.startswith("FAIL")]
    status = NEEDS_HUMAN  # both FAIL and WARN go to the agent worklist; bar-tripping is ant-tier (none here)
    return {"name": name, "status": status,
            "detail": f"{len(hits)} {label} drift item(s) ({len(fails)} fail)",
            "actions": [h[:160] for h in hits[:5]] + ["reconcile via scripts/agent-work.py + correct-state"]}


def heal_reconcile_safe(apply):
    """#345: auto-apply the mechanically-safe reconcile repairs in the daily harness.

    reconcile.py --fix touches ONLY the fixable invariants — I1 (live lease on a
    done/terminal task), I2 (duplicate leases on one task), I5 (crash-orphaned
    in_progress tasks) — all idempotent, reversible lease releases via the
    audited agent-work.py mutator. Folding it into self-heal's --apply means the
    lease/drift family is auto-healed by the canonical daily harness, not only by
    the queue-runner sweep (feedback_self_heal_autonomy: broaden auto-fix to the
    mechanical+safe+reversible class). The judgment-laden invariants (I4/I6/I7/I8)
    stay DETECT-only in check_lease_invariants/check_taskstate_drift below.
    """
    mode = ["--fix", "--apply"] if apply else ["--fix"]
    rc, out = sh([sys.executable, os.path.join(REPO, "scripts", "reconcile.py"), *mode], timeout=120)
    lines = [l.strip() for l in out.splitlines() if l.strip()]
    if rc != 0:
        return {"name": "reconcile-safe", "status": NEEDS_HUMAN,
                "detail": f"reconcile --fix exited {rc}", "actions": lines[-3:] or [out[:160]]}
    # reconcile prints "N fix(es) planned" (dry-run) or "N fix(es) applied" (--apply);
    # parse the count so the literal "0 fix(es) planned" no-op isn't read as drift.
    m = re.search(r"(\d+)\s+fix\(es\)\s+(planned|applied)", out)
    count = int(m.group(1)) if m else 0
    if count == 0:
        return {"name": "reconcile-safe", "status": OK,
                "detail": "no fixable lease/state drift", "actions": []}
    detail_lines = [l for l in lines if "released" in l.lower() or "corrected" in l.lower()
                    or re.match(r"\s*[-•]?\s*I\d", l)]
    if apply:
        return {"name": "reconcile-safe", "status": HEALED,
                "detail": f"auto-applied {count} safe reconcile repair(s) (I1/I2/I5)",
                "actions": detail_lines[:5] or lines[-3:]}
    return {"name": "reconcile-safe", "status": NEEDS_HUMAN,
            "detail": f"{count} fixable lease/state drift item(s) (dry-run)",
            "actions": detail_lines[:5] or lines[-3:]}


def heal_lease_reap(apply):
    """Checkout-ledger bloat (2026-07-08 flood): queue-runner claims with
    session="manual" accumulate as terminal records forever because nothing
    scheduled `agent-work.py reap` — active-checkouts.json hit 1269 records
    (299 dupes on one task) before the first manual prune. Reap is mechanical,
    idempotent, and touches only expired/terminal records via the locked
    mutator, so it belongs in Layer-A. Tuning (measured 2026-07-08): queue-runner
    churns ~144 records/day, so 2-day retention bounds the ledger near ~300
    records and the alert threshold sits at 400; git history keeps the full
    audit trail beyond that window."""
    path = os.path.join(REPO, "docs/process/state/active-checkouts.json")
    try:
        with open(path, encoding="utf-8") as f:
            recs = json.load(f).get("checkouts", [])
    except (OSError, ValueError) as e:
        return {"name": "lease-reap", "status": NEEDS_HUMAN,
                "detail": f"active-checkouts.json unreadable: {e}", "actions": []}
    terminal = [r for r in recs if r.get("status") in ("released", "expired", "stolen")]
    if len(terminal) <= 400:
        return {"name": "lease-reap", "status": OK,
                "detail": f"checkout ledger healthy ({len(recs)} records, {len(terminal)} terminal)",
                "actions": []}
    if not apply:
        return {"name": "lease-reap", "status": NEEDS_HUMAN,
                "detail": f"{len(terminal)} terminal checkout record(s) — reap needed (dry-run)",
                "actions": ["python3 scripts/agent-work.py reap --prune-terminal --older-than 2"]}
    rc, out = sh([sys.executable, os.path.join(REPO, "scripts", "agent-work.py"),
                  "reap", "--prune-terminal", "--older-than", "2"], timeout=60)
    if rc != 0:
        return {"name": "lease-reap", "status": NEEDS_HUMAN,
                "detail": f"reap exited {rc}", "actions": [out[:160]]}
    return {"name": "lease-reap", "status": HEALED,
            "detail": f"reaped checkout ledger ({len(terminal)} terminal records before)",
            "actions": [out.strip()[:160]]}


def check_lease_invariants(apply):
    """Lease/checkout/fence drift (I5/I6) — the active-checkouts conflict-loop class.
    Detection of the non-auto-fixable residue; heal_reconcile_safe applies I5."""
    return _invariant_finding("lease-drift", [5, 6], "lease")


def check_taskstate_drift(apply):
    """Task-state ↔ projection ↔ working-context drift (I4/I7/I8)."""
    return _invariant_finding("taskstate-drift", [4, 7, 8], "task-state")


def check_dashboard_contract(apply):
    """Dashboard /api/all field contract (detail.js silent-break class). Detection only;
    a restart is heavier than a daily heal should blind-fire, so agent-tier."""
    rc, out = sh(["bash", os.path.join(REPO, "scripts", "smoke-api-all.sh")], timeout=60)
    if rc == 0:
        return {"name": "dashboard-contract", "status": OK, "detail": "/api/all contract OK", "actions": []}
    last = [l.strip() for l in out.splitlines() if "FAIL" in l or "unreachable" in l][-2:]
    return {"name": "dashboard-contract", "status": NEEDS_HUMAN, "detail": "/api/all contract broken or dashboard down",
            "actions": last + ["investigate; if down: bash scripts/restart-dashboard.sh"]}


def check_detector_gaps(apply):
    """Surface bugs recorded (via add-healthcheck.py --gap) as not-yet-mechanically-
    detectable, so 'we'll add a detector later' doesn't vanish — it stays on the worklist
    until someone writes the check or confirms it's obsolete."""
    try:
        gaps = json.load(open(HEALTH_CHECKS_FILE)).get("gaps", [])
    except Exception:
        gaps = []
    if not gaps:
        return {"name": "detector-gaps", "status": OK, "detail": "no open detector gaps", "actions": []}
    return {"name": "detector-gaps", "status": NEEDS_HUMAN,
            "detail": f"{len(gaps)} bug(s) without a mechanical detector",
            "actions": [f"{g['name']}: {g.get('reason','')} — write a check or close the gap" for g in gaps[:5]]}


def heal_claude_keychain(apply):
    """HYBRID auth model (changed 2026-06-30 — was: token-only, auto-DELETE keychain creds).
    The fleet still runs on the inference-only env token (CLAUDE_CODE_OAUTH_TOKEN in
    ~/.claude-oauth.env), which SHADOWS the keychain in current CC (env wins) — so a present
    'Claude Code-credentials' entry no longer harms the fleet. That entry is now LOAD-BEARING:
    it's the full-scope `claude auth login` credential the carve-out RC session
    (scripts/claude-rc.sh / `ccrc`) needs for Claude Code Remote Control. Auto-deleting it is
    what broke RC four times, so this check now PRESERVES it: present = OK (RC ready), absent =
    advisory (fleet fine via env token, RC unavailable). It NEVER deletes. Never touch
    'Claude Safe Storage' (the desktop app key). See memory project-claude-oauth-token-fix
    (hybrid section). macOS only; no-op elsewhere."""
    if sys.platform != "darwin":
        return {"name": "claude-keychain", "status": OK, "detail": "not macOS", "actions": []}
    tokfile = os.path.join(HOME, ".claude-oauth.env")
    has_token = os.path.exists(tokfile) and "CLAUDE_CODE_OAUTH_TOKEN" in open(tokfile).read()
    _, dump = sh(["bash", "-lc", "security dump-keychain 2>/dev/null | grep -i '\"svce\"'"])
    names = sorted(set(re.findall(r'"svce"<blob>="(Claude Code-credentials[^"]*)"', dump)))
    if names:
        # PRESERVE — this is the RC carve-out's full-scope login. Do not delete.
        return {"name": "claude-keychain", "status": OK,
                "detail": f"RC keychain cred present ({', '.join(names)}) — preserved for the ccrc carve-out; "
                          f"fleet uses the env token{' (present)' if has_token else ' (MISSING — see below)'}",
                "actions": [] if has_token else
                           ["fleet token missing: ~/.local/bin/claude setup-token, then recreate ~/.claude-oauth.env (chmod 600)"]}
    # no keychain cred
    if not has_token:
        return {"name": "claude-keychain", "status": NEEDS_HUMAN, "escalation": ANT,
                "detail": "no RC keychain cred AND ~/.claude-oauth.env token missing — next claude will force /login",
                "actions": ["restore fleet: ~/.local/bin/claude setup-token, then recreate ~/.claude-oauth.env (chmod 600)"]}
    return {"name": "claude-keychain", "status": OK,
            "detail": "fleet token-only auth intact (env token present); RC keychain cred absent — "
                      "Remote Control unavailable until `ccrc` + `claude auth login`",
            "actions": []}


# <<MACHINE_1_ID>>'s Ollama must host ONLY the small arbiter + embed models. A second BIG model
# co-resident with the always-on MLX lane (~18GB) blows the macOS GPU budget (~48GB =
# 75% of 64GB) → kIOGPUCommandBufferCallbackErrorOutOfMemory + jetsam → WindowServer
# starves → SCREENS GLITCH (also kills lanes/verdicts/embeds). The screen-glitch bug
# recurred 2026-06-26 even after the queue-runner arbiter was right-sized to qwen3:8b,
# because a STALE caller (<<MACHINE_2_ID>>'s old queue-runner, src <<MACHINE_2_TAILSCALE_IP>>) kept loading
# qwen3-coder:30b at its 262k default ctx (33GB) onto <<MACHINE_1_ID>>'s Ollama — a config fix
# on one machine can't stop another machine's stale caller. The structural cure is to
# REMOVE the big blobs so any such call 404s ("model not found", loads nothing) instead
# of OOMing. This heal enforces that allowlist so a stray re-pull self-heals.
# See memory project_mlx_lane_runtime.
OLLAMA_ALLOWLIST = ("qwen3:8b", "nomic-embed-text")  # arbiter + embed; everything else is liability
OLLAMA_OOM_GB = 10.0  # only models this big are a GPU-OOM risk; small strays are reported, not removed


def heal_ollama_allowlist(apply):
    """Enforce <<MACHINE_1_ID>>'s right-sized Ollama: arbiter (qwen3:8b) + embed (nomic-embed-text)
    ONLY. Auto-remove any non-allowlisted model >= OLLAMA_OOM_GB (the co-resident-OOM
    risk class that glitches the screens). No-op where the ollama CLI is absent."""
    rc, out = sh(["bash", "-lc", "command -v ollama >/dev/null 2>&1 && ollama list || echo __NO_OLLAMA__"])
    if "__NO_OLLAMA__" in out or rc != 0:
        return {"name": "ollama-allowlist", "status": OK, "detail": "ollama not present", "actions": []}
    liabilities, small_strays = [], []
    for line in out.splitlines()[1:]:  # skip header
        if not line.strip():
            continue
        name = line.split()[0]
        if any(name == a or name.startswith(a + ":") for a in OLLAMA_ALLOWLIST):
            continue
        m = re.search(r"(\d+(?:\.\d+)?)\s*(TB|GB|MB)", line)
        gb = 0.0
        if m:
            val, unit = float(m.group(1)), m.group(2)
            gb = val * (1024 if unit == "TB" else 1 if unit == "GB" else 1 / 1024)
        (liabilities if gb >= OLLAMA_OOM_GB else small_strays).append((name, gb))
    extra = []
    if small_strays:
        extra = [f"non-allowlisted small model(s) present (not an OOM risk, left in place): "
                 + ", ".join(f"{n} ({g:.1f}GB)" for n, g in small_strays)]
    if not liabilities:
        return {"name": "ollama-allowlist", "status": OK,
                "detail": "ollama hosts only arbiter+embed (no big co-resident OOM risk)", "actions": extra}
    names = ", ".join(f"{n} ({g:.0f}GB)" for n, g in liabilities)
    if apply:
        removed = []
        for n, _g in liabilities:
            r, _o = sh(["ollama", "rm", n])
            if r == 0:
                removed.append(n)
        if len(removed) == len(liabilities):
            return {"name": "ollama-allowlist", "status": HEALED,
                    "detail": f"removed big non-allowlisted ollama model(s) that risk GPU-OOM/screen-glitch: {names}",
                    "actions": [f"removed: {', '.join(removed)}",
                                "if a caller needs it: it now 404s (loads nothing) — fix the caller, don't re-pull"] + extra}
        return {"name": "ollama-allowlist", "status": NEEDS_HUMAN, "escalation": AGENT,
                "detail": f"tried to remove big ollama liabilit(ies) but some remain: {names}",
                "actions": ["manual: ollama rm <name>"] + extra}
    return {"name": "ollama-allowlist", "status": NEEDS_HUMAN, "escalation": AGENT,
            "detail": f"big non-allowlisted ollama model(s) present — co-resident OOM/screen-glitch risk: {names}",
            "actions": ["heal: re-run with --apply (auto-removes them)",
                        "root cause: a stale caller pulled a big model onto <<MACHINE_1_ID>>'s Ollama (memory project_mlx_lane_runtime)"] + extra}


def check_claude_auth_status(apply):
    """Surface a RED Claude-auth verdict (from verify-claude-auth.sh's RunAtLoad run) into
    the AGENT worklist, so a session auto-picks it up instead of Ant having to notice+relay.
    The verify script already auto-recovers a clobbered token from its backup; a status of
    'fail' here means it could NOT self-recover (token expired → needs interactive
    `claude setup-token`, which only Ant can run). Read-only: the verify script owns heal."""
    status_file = os.path.join(HOME, ".openclaw", "claude-auth-verify.status")
    if not os.path.exists(status_file):
        return {"name": "claude-auth", "status": OK, "detail": "no verify run yet (verify-claude-auth.sh)", "actions": []}
    try:
        s = json.load(open(status_file))
    except Exception:
        return {"name": "claude-auth", "status": OK, "detail": "auth status unreadable (ignored)", "actions": []}
    if s.get("state") == "ok":
        return {"name": "claude-auth", "status": OK,
                "detail": f"auth healthy on {s.get('host','?')} ({s.get('reason','')})", "actions": []}
    host = s.get("host", "?")
    return {"name": "claude-auth", "status": NEEDS_HUMAN, "escalation": AGENT,
            "detail": f"Claude auth RED on {host} and self-recovery failed: {s.get('reason','?')}",
            "actions": [f"triage {host}: run scripts/verify-claude-auth.sh to confirm",
                        f"if token EXPIRED → only Ant can fix: `claude setup-token` on {host}, then recreate ~/.claude-oauth.env (chmod 600)",
                        "if a peer machine still has a valid token, copy ~/.claude-oauth.env across to recover without setup-token"]}


HEALS = [heal_symlinks, heal_hook_exec, check_hook_wiring, check_mirror_drift, check_stray_git,
         check_gitsync_drift, heal_autosync, heal_poller, heal_relay_poller, heal_tag_intake, check_lane_bloat,
         heal_stale_tmux_sessions, heal_ollama_allowlist,
         heal_lease_reap, heal_reconcile_safe, check_lease_invariants, check_taskstate_drift,
         check_dashboard_contract, check_detector_gaps, heal_claude_keychain,
         check_claude_auth_status]


# ──────────── declarative command-checks (the self-growing registry) ───────────

def _make_command_check(spec):
    """Turn a health-checks.json entry into a check fn. A command-check passes when its
    cmd exits ok_exit; otherwise it's a finding at the spec's tier (default agent)."""
    ok_exit = int(spec.get("ok_exit", 0))
    timeout = int(spec.get("timeout", 60))

    def _check(apply):
        rc, out = sh(["bash", "-lc", spec["cmd"]], timeout=timeout)
        if rc == ok_exit:
            return {"name": spec["name"], "status": OK,
                    "detail": spec.get("ok_detail", f"{spec['name']} ok"), "actions": []}
        ref = f" (regresses {spec['bug_ref']})" if spec.get("bug_ref") else ""
        # Optional declarative self-heal: in apply mode, run heal_cmd and re-check.
        if apply and spec.get("heal_cmd"):
            sh(["bash", "-lc", spec["heal_cmd"]], timeout=timeout)
            rc2, _ = sh(["bash", "-lc", spec["cmd"]], timeout=timeout)
            if rc2 == ok_exit:
                return {"name": spec["name"], "status": HEALED,
                        "detail": spec.get("fail_detail", spec["name"]) + ref + " — auto-healed",
                        "actions": [f"ran heal: {spec['heal_cmd']}"]}
        tail = [l.strip() for l in out.splitlines() if l.strip()][-3:]
        return {"name": spec["name"], "status": NEEDS_HUMAN,
                "detail": spec.get("fail_detail", f"{spec['name']} check failed") + ref,
                "actions": tail + list(spec.get("actions", [])),
                "escalation": spec.get("tier", AGENT)}
    _check.__name__ = "cmd_" + re.sub(r"[^0-9a-zA-Z]+", "_", spec["name"])
    return _check


def load_command_checks():
    try:
        specs = json.load(open(HEALTH_CHECKS_FILE)).get("checks", [])
    except Exception:
        return []
    out = []
    for s in specs:
        if isinstance(s, dict) and s.get("name") and s.get("cmd") and not s.get("disabled"):
            out.append(_make_command_check(s))
    return out


def run_check(fn, apply):
    """Fault-isolate a single check: a check that throws or returns a bad shape becomes a
    NEEDS_HUMAN finding about itself, never killing the whole run (a blind spot is worse
    than a noisy one)."""
    try:
        r = fn(apply)
        if not isinstance(r, dict) or "name" not in r or "status" not in r:
            raise ValueError(f"bad result shape: {r!r}")
        r.setdefault("detail", "")
        r.setdefault("actions", [])
        return r
    except Exception as e:
        return {"name": getattr(fn, "__name__", "unknown-check"), "status": NEEDS_HUMAN,
                "detail": f"CHECK ERRORED: {e}", "escalation": AGENT,
                "actions": ["a broken check is a blind spot — fix the check fn/spec"]}


# ───────────────────────── LAYER B — compliance meters ───────────────────────

def _load_gate_log(hours=24):
    if not os.path.exists(GATE_LOG):
        return []
    cutoff = datetime.datetime.now() - datetime.timedelta(hours=hours)
    out = []
    for line in open(GATE_LOG):
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
            ts = datetime.datetime.fromisoformat(r.get("ts", ""))
        except Exception:
            continue
        if ts >= cutoff:
            out.append(r)
    return out


def meter_signoff(recs):
    """Sign-off standard adherence + false-positive surfacing (the FP loop).

    - block_rate: share of stops the gate had to intervene on (trend; high = the
      model still isn't emitting the block inline).
    - fp_candidates: blocks whose closing text already LOOKED like a sign-off the
      regex rejected (header present but fields didn't match, or ≥2 field words in
      the tail). These are exactly the cases that need a regex tweak — surfaced with
      their tails so the fix is a copy-paste, never auto-applied.
    """
    g = [r for r in recs if r.get("session") and r.get("decision")]
    total = len(g)
    blocks = [r for r in g if r["decision"] == "block"]
    # A TRUE false-positive candidate = a block where the FULL sign-off shape was
    # plausibly present but a gate regex rejected it. Two shapes qualify:
    #   1. header matched but fields didn't → field-regex miss candidate;
    #   2. field labels present AND a header-LIKE bold line (`**…** — …`) in the
    #      tail → header-regex miss candidate.
    # Field words ALONE are not enough: a stop ending `- Next: …` with no header at
    # all is genuine non-compliance (the 07fd0e09 class, reviewed 2026-06-11) and
    # belongs in the block_rate trend, not a daily FP ALERT. (A bare header match is
    # likewise too loose: stray bold-with-separator prose like `**Read + Insert**`.)
    fieldword = re.compile(r"\b(Done|Verified|Check|Next|Asks)\b\s*:", re.I)
    # Line-anchored: a real header opens its own line; mid-sentence bolds like
    # "My lean: **build the bridge** — it's…" must not qualify.
    headerlike = re.compile(r"^\s*\*\*[^*\n]+\*\*\s*(?:—|--)\s*\S", re.M)
    # Either way the MISSING half must look present to a looser regex — h=T alone
    # is a stray prose bold (0a111d59: `**Action required…**` in a warden verdict),
    # f-words alone are a fieldless prose mention.
    fp = []
    for b in blocks:
        tail = b.get("tail", "")
        if b.get("header_match") and not b.get("fields_match") and fieldword.search(tail):
            fp.append(b)
        elif b.get("fields_match") and not b.get("header_match") and headerlike.search(tail):
            fp.append(b)
    block_rate = (len(blocks) / total) if total else 0.0
    # ALERT if any false-positive candidate (regex needs tuning) — the headline ask.
    status = ALERT if fp else PASS
    detail = f"{total} stops/24h · {len(blocks)} blocked ({block_rate:.0%}) · {len(fp)} FP-candidate(s)"
    samples = [{"session": b.get("session", "")[:8],
                "header_match": b.get("header_match"), "fields_match": b.get("fields_match"),
                "tail": b.get("tail", "")[-200:]} for b in fp[:5]]
    return {"name": "signoff-compliance", "status": status, "score": round(1 - block_rate, 3),
            "threshold": "0 FP-candidates", "detail": detail, "samples": samples}


def meter_taxonomy(recs):
    """Drift between tasks.json and the canonical taxonomy SoT (docs/process/taxonomy.yaml):
    off-vocab domain/status or a project with no domain mapping. 0 = clean.

    The taxonomy validator + its SoT are an OPTIONAL overlay (the vocab is
    org/personal-specific; a portable consumer may not ship one). A missing file
    must SKIP this meter, not crash the whole self-heal harness — so guard both the
    validator script and the SoT, and fail soft on any load/scan error."""
    import importlib.util
    lint_path = os.path.join(REPO, "scripts", "taxonomy-lint.py")
    sot_path = os.path.join(REPO, "docs/process", "taxonomy.yaml")
    skip = {"name": "taxonomy-drift", "status": PASS, "score": 1,
            "threshold": "0 off-vocab", "detail": "taxonomy SoT/validator absent — skipped", "samples": []}
    if not (os.path.exists(lint_path) and os.path.exists(sot_path)):
        return skip
    try:
        spec = importlib.util.spec_from_file_location("taxonomy_lint", lint_path)
        tx = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(tx)
        findings = tx._scan_tasks()
    except Exception as e:
        return {**skip, "detail": f"taxonomy lint unavailable — skipped ({e})"}
    status = ALERT if findings else PASS
    return {"name": "taxonomy-drift", "status": status, "score": 0 if findings else 1,
            "threshold": "0 off-vocab", "detail": f"{len(findings)} taxonomy drift finding(s) vs canonical vocab",
            "samples": findings[:5]}


def meter_inbox_quality(recs):
    """Thin Ant-decisions (#326-A safety-net): an owner=ant decision-point that is
    open + undecided but LACKS the structured fields #323 needs to render a clean
    one-tap card — decisionOptions, recommendation, or decisionContext. Without
    them it regresses to a crude regex Yes/No card in the inbox. 0 = every genuine
    Ant-decision is properly structured.

    Detective only — flags thin decisions for enrichment, never blocks authoring.
    Fails soft if the task store is absent/unreadable (a portable consumer may not
    ship one), matching meter_taxonomy's optional-overlay contract."""
    tasks_path = os.path.join(REPO, "docs/process/state/tasks.json")
    skip = {"name": "inbox-quality", "status": PASS, "score": 1,
            "threshold": "0 thin Ant-decisions",
            "detail": "task store absent — skipped", "samples": []}
    if not os.path.exists(tasks_path):
        return skip
    try:
        d = json.load(open(tasks_path))
        ts = d.get("tasks", d)
        ts = list(ts.values()) if isinstance(ts, dict) else ts
    except Exception as e:
        return {**skip, "detail": f"task store unreadable — skipped ({e})"}
    TERMINAL = {"done", "cancelled", "archived"}
    thin = []
    for t in ts:
        if t.get("state") in TERMINAL:
            continue
        if (t.get("owner") or "").strip().lower() != "ant":
            continue
        if (t.get("decision") or "").strip():
            continue  # already decided — the point is closed
        ndp = (t.get("nextDecisionPoint") or "").strip()
        is_decision = (bool(ndp) and not re.match(r"none\b", ndp, re.I)) or bool(t.get("decisionOptions"))
        if not is_decision:
            continue
        missing = [f for f in ("decisionOptions", "recommendation", "decisionContext") if not t.get(f)]
        if missing:
            thin.append(f"{t.get('taskId')} missing {','.join(missing)}")
    status = ALERT if thin else PASS
    return {"name": "inbox-quality", "status": status, "score": 0 if thin else 1,
            "threshold": "0 thin Ant-decisions",
            "detail": f"{len(thin)} owner=ant decision(s) lacking structured #323 fields",
            "samples": thin[:5]}


def meter_notion_domain_vocab(recs):
    """Notion Command Center Domain vocab drift (#644 aftermath): the DB's Domain
    select options must stay within the canonical life-domain vocabulary
    (docs/process/taxonomy.yaml `domains:`). Notion auto-creates a select option
    the first time any writer sends an off-vocab string, and select names match
    case-insensitively — so one legacy writer silently re-seeds the old vocab
    ('Engineering', 'business', …) and every later card can snap to it. One GET,
    no card scan; heal = python3 scripts/notion-remap-domains.py --write.
    Fail-soft: no token / no network / missing SoT skips the meter."""
    skip = {"name": "notion-domain-vocab", "status": PASS, "score": 1,
            "threshold": "0 off-vocab Domain options",
            "detail": "notion not configured / unreachable — skipped", "samples": []}
    sot = os.path.join(REPO, "docs/process/taxonomy.yaml")
    if not os.path.exists(sot):
        return skip
    try:
        import importlib.util as _ilu
        import yaml as _yaml
        canon = set((_yaml.safe_load(open(sot).read()) or {}).get("domains") or {})
        spec = _ilu.spec_from_file_location("notion_cc", os.path.join(REPO, "scripts", "notion_cc.py"))
        cc = _ilu.module_from_spec(spec)
        spec.loader.exec_module(cc)
        tok = cc.token()
        if not (canon and tok):
            return skip
        ok, db = cc.request(tok, "GET", f"/databases/{cc.DB_ID}", None)
        if not ok:
            return {**skip, "detail": f"notion GET failed — skipped ({str(db)[:80]})"}
        opts = {o["name"] for o in db["properties"]["Domain"]["select"]["options"]}
    except Exception as e:
        return {**skip, "detail": f"notion vocab check unavailable — skipped ({e})"}
    off = sorted(opts - canon)
    status = ALERT if off else PASS
    return {"name": "notion-domain-vocab", "status": status, "score": 0 if off else 1,
            "threshold": "0 off-vocab Domain options",
            "detail": (f"{len(off)} off-vocab Domain option(s) in the CC DB — a writer is "
                       "seeding legacy vocab; run scripts/notion-remap-domains.py --write"
                       if off else "CC Domain options all canonical"),
            "samples": off[:8]}


def meter_curator_format(recs):
    """Arbiter JSON discipline (#333): count 'Arbiter returned invalid JSON' /
    'no JSON object' lines in the queue-runner log from the last 24h. Lanes
    imitate formats present in reviewed content (the sign-off-block leak found
    2026-06-12: warden/arbiter answered in block format after reviewing the
    self-heal audit doc, which quotes meter_signoff patterns), and a malformed
    arbiter verdict silently degrades the quality gate to a retry. #332's
    raw_decode tolerates trailing prose; this catches the cases it can't.
    Fails soft when the log is absent (runner not installed here)."""
    import time as _time
    log_path = os.path.expanduser("~/.openclaw/logs/queue-runner.log")
    skip = {"name": "arbiter-format", "status": PASS, "score": 1,
            "threshold": "0 parse failures/24h",
            "detail": "queue-runner log absent — skipped", "samples": []}
    if not os.path.exists(log_path):
        return skip
    try:
        if os.path.getmtime(log_path) < _time.time() - 24 * 3600:
            return {**skip, "detail": "queue-runner log stale (>24h) — skipped"}
        bad = []
        with open(log_path, errors="replace") as f:
            for line in f.readlines()[-4000:]:
                if "Arbiter returned invalid JSON" in line or "Arbiter returned no JSON object" in line:
                    bad.append(line.strip()[:160])
    except Exception as e:
        return {**skip, "detail": f"queue-runner log unreadable — skipped ({e})"}
    status = ALERT if bad else PASS
    return {"name": "arbiter-format", "status": status, "score": 0 if bad else 1,
            "threshold": "0 parse failures/24h",
            "detail": f"{len(bad)} arbiter JSON parse failure(s) in recent runner log",
            "samples": bad[-5:]}


def meter_headless_model_pin(recs):
    """Unpinned headless `claude -p` callers (2026-07-04 burn): a scheduled script
    that invokes `claude -p` WITHOUT `--model` inherits the interactive default
    from ~/.claude/settings.json — one /model switch to a premium tier (fable-5)
    silently multiplied the 08:30 system-audit's cost and burned ~75% of a shared
    5h window before wake. Every headless caller must pin its own model
    (model-effort-and-routing-standard.md). Detective only; file-level check
    (invokes `claude`/`$CLAUDE_BIN` with -p somewhere AND has --model somewhere).
    Fails soft on unreadable files."""
    import glob as _glob
    roots = [os.path.join(REPO, "scripts", "*.sh"),
             os.path.expanduser("~/.local/bin/*")]
    invoke = re.compile(r'(\bclaude\b|\$\{?CLAUDE_BIN\}?"?)\s+(-p|--print)\b')
    unpinned = []
    for pat in roots:
        for path in _glob.glob(pat):
            real = os.path.realpath(path)
            if not os.path.isfile(real):
                continue
            # shell scripts only: python callers build argv lists this regex can't
            # see, and their doc strings (metis-status.py's job table) false-positive
            if real.endswith(".py"):
                continue
            try:
                with open(real, errors="replace") as f:
                    lines = f.readlines()
            except Exception:
                continue
            # comment lines don't count as invocations (metis-status documents
            # the scheduled `claude -p` jobs in comments/strings without calling one);
            # join backslash-continued lines so multi-line invocations
            # (claude-task.sh style: `claude \` / `--print \`) still match.
            code = "\n".join(l for l in lines if not l.lstrip().startswith("#"))
            code = code.replace("\\\n", " ")
            if invoke.search(code) and "--model" not in code:
                unpinned.append(os.path.basename(path))
    unpinned = sorted(set(unpinned))
    status = ALERT if unpinned else PASS
    return {"name": "headless-model-pin", "status": status,
            "score": 0 if unpinned else 1,
            "threshold": "0 unpinned headless claude -p callers",
            "detail": f"{len(unpinned)} script(s) call claude -p without --model "
                      "(inherit interactive settings.json model)",
            "samples": unpinned[:5]}


def meter_whisper_stt(recs):
    """Voice dictation STT health (#574).

    <<MACHINE_1_ID>> hosts whisper.cpp on loopback :3762 and exposes it through the Metis
    Caddy front door at /stt/. <<MACHINE_2_ID>> should NOT run/download its own model; it
    probes <<MACHINE_1_ID>>'s tailnet front door instead. <<MACHINE_1_ID>> still probes loopback and
    can kickstart the LaunchAgent. Any HTTP response means the server path is
    alive; only connection failures count as down.
    """
    import urllib.request as _rq
    import socket as _socket
    user = os.environ.get("USER") or ""
    host = (_socket.gethostname() or "").lower()
    on_hearth = user == "Ant" or "<<MACHINE_1_ID>>" in host
    url = os.environ.get("WHISPER_STT_HEALTH_URL") or (
        "http://127.0.0.1:3762/" if on_hearth else "http://<<MACHINE_1_TAILSCALE_IP>>:3749/stt/"
    )
    try:
        _rq.urlopen(url, timeout=5)
        up = True
    except Exception as e:
        up = getattr(e, "code", None) is not None
    if not up and on_hearth:
        subprocess.run(["launchctl", "kickstart", "-k",
                        f"gui/{os.getuid()}/ai.openclaw.whisper-server"],
                       capture_output=True, check=False)
    status = PASS if up else ALERT
    where = "<<MACHINE_1_ID>>-local" if on_hearth else "<<MACHINE_1_ID>> front-door"
    return {"name": "whisper-stt", "status": status,
            "score": 1 if up else 0,
            "threshold": f"{where} whisper endpoint answering at {url}",
            "detail": "voice dictation STT " + ("healthy" if up else
                      "DOWN — cockpit mic falls back to cloud SR"),
            "samples": []}


def meter_kokoro_tts(recs):
    """Conversation-mode TTS health (#591).

    <<MACHINE_1_ID>> hosts the Kokoro voice server on loopback :3763; the cockpit proxies
    it at /api/voice/tts. Down is non-fatal (speak() falls back to browser
    speechSynthesis) but degrades the voice — heal it like whisper. <<MACHINE_2_ID>>
    probes the cockpit proxy through the front door (405 on GET still proves
    the path is alive); <<MACHINE_1_ID>> probes loopback and can kickstart.
    """
    import urllib.request as _rq
    import socket as _socket
    user = os.environ.get("USER") or ""
    host = (_socket.gethostname() or "").lower()
    on_hearth = user == "Ant" or "<<MACHINE_1_ID>>" in host
    url = os.environ.get("KOKORO_TTS_HEALTH_URL") or (
        "http://127.0.0.1:3763/" if on_hearth
        else "https://<<MACHINE_1_HOSTNAME>>.tailbe5cff.ts.net/api/voice/tts"
    )
    try:
        _rq.urlopen(url, timeout=5)
        up = True
    except Exception as e:
        up = getattr(e, "code", None) is not None
    if not up and on_hearth:
        subprocess.run(["launchctl", "kickstart", "-k",
                        f"gui/{os.getuid()}/ai.openclaw.kokoro-tts"],
                       capture_output=True, check=False)
    status = PASS if up else ALERT
    where = "<<MACHINE_1_ID>>-local" if on_hearth else "<<MACHINE_1_ID>> front-door"
    return {"name": "kokoro-tts", "status": status,
            "score": 1 if up else 0,
            "threshold": f"{where} Kokoro TTS endpoint answering at {url}",
            "detail": "conversation voice " + ("healthy" if up else
                      "DOWN — replies fall back to robotic speechSynthesis"),
            "samples": []}


def meter_web_brain_reachable(recs):
    """Web Metis assistant never-down health (#581).

    Ant runs everything through the metis-command web assistant while traveling;
    it must never go dark. The route now falls through a reliability-first ladder
    (Claude -> Codex -> local MLX/gateway), so the brain is DARK only when the app
    itself is down OR *every* rung is unavailable. This is a free reachability
    probe (no brain POST, no token spend) — the token-spending end-to-end check is
    scripts/metis-brain-selftest.sh, run on demand. <<MACHINE_1_ID>>-only (the app + brain
    backends live here); <<MACHINE_2_ID>> PASSes (it drives <<MACHINE_1_ID>>'s brain remotely).
    """
    import urllib.request as _rq
    import socket as _socket
    user = os.environ.get("USER") or ""
    host = (_socket.gethostname() or "").lower()
    on_hearth = user == "Ant" or "<<MACHINE_1_ID>>" in host
    if not on_hearth:
        return {"name": "web-brain-reachable", "status": PASS, "score": 1,
                "threshold": "<<MACHINE_1_ID>>-only meter (brain surface lives on <<MACHINE_1_ID>>)",
                "detail": "skipped on <<MACHINE_2_ID>>", "samples": []}

    def _up(url, timeout=4):
        try:
            _rq.urlopen(url, timeout=timeout); return True
        except Exception as e:
            return getattr(e, "code", None) is not None  # any HTTP response = up
    def _port_open(port, timeout=3):
        try:
            with _socket.create_connection(("127.0.0.1", port), timeout=timeout):
                return True
        except Exception:
            return False

    app_up = _up(f"http://127.0.0.1:{os.environ.get('MC_PORT','3747')}/")
    # rung availability (mirrors metis.sh / brain-rungs.ts): claude budget usable,
    # gateway listening, MLX serving. ANY one available => brain can answer.
    claude_5h = None
    try:
        out = subprocess.run(["python3", os.path.join(REPO, "scripts/lib/claude_budget.py")],
                             capture_output=True, text=True, timeout=8).stdout
        claude_5h = json.loads(out).get("5h")
    except Exception:
        claude_5h = None
    min5h = int(os.environ.get("METIS_MIN_5H_PCT", "8"))
    claude_rung = (claude_5h is None) or (isinstance(claude_5h, (int, float)) and claude_5h >= min5h)
    gateway_up = _port_open(18789)
    mlx_up = _up("http://127.0.0.1:8081/v1/models")
    rungs_up = [n for n, ok in (("claude", claude_rung), ("gateway", gateway_up), ("mlx", mlx_up)) if ok]

    dark = (not app_up) or (len(rungs_up) == 0)
    status = ALERT if dark else PASS
    if not app_up:
        detail = "metis-command app DOWN — web brain unreachable (restart metis-command)"
    elif not rungs_up:
        detail = "app up but ALL rungs down (claude budget spent, gateway + MLX down) — brain will go dark"
    else:
        detail = f"web brain up; rungs available: {', '.join(rungs_up)} (5h={claude_5h})"
    return {"name": "web-brain-reachable", "status": status,
            "score": 0 if dark else 1,
            "threshold": "app up AND >=1 rung (claude|gateway|mlx) available",
            "detail": detail,
            "actions": (["restart metis-command; then bash scripts/metis-brain-selftest.sh"] if dark else []),
            "samples": rungs_up[:3]}


# --- doc-truth meter (#514): protocol docs must not teach forbidden operations ----------
_DOC_TRUTH_GLOBS = ["docs/process/*.md", "ClaudeCode/skills/**/*.md"]
_DOC_TRUTH_BANNED = [
    ("ollama-lanes", re.compile(r"\bOllama lanes?\b", re.I)),
    ("legacy-board-checkbox", re.compile(r"^\s*[-*]\s+\[P[0-9]\]\s*\[[ xX]?\]")),
    ("illegal-transition-in_progress->done",
     re.compile(r"in_progress\s*(?:->|-->|→|\bto\b)\s*`?done", re.I)),
    ("projection-hand-edit",
     re.compile(r"(?:write|log|add|append|entr(?:y|ies)|prune|check the box|move it)"
                r"[^\n]{0,48}(?:task-queue\.md|OPEN_TASKS\.md)", re.I)),
]
# Negated / explanatory / self-referential mentions are not violations (e.g.
# "never hand-edit task-queue.md", "there is no in_progress -> done", the meter's own doc).
_DOC_TRUTH_EXEMPT = re.compile(
    r"never|don'?t|do not|not by hand|no\s+`?in_progress|re-?render|regenerat|projection|"
    r"read-only|overwrit|owns the|instead of|rather than|legacy|retired|deprecat|banned|"
    r"forbidden|old format|drift|meter|#514|reject|illegal|invalid|wrong|must not|no longer", re.I)


def meter_doc_truth(recs):
    """Doc-vs-contract drift in the highest-traffic protocol surfaces (#514). Greps the
    close/lifecycle/state docs + skills for prose that teaches forbidden operations:
    'Ollama lanes' (the lane runtime is MLX-LM), the retired '- [P2] [ ]' board format,
    the illegal in_progress->done transition (done is only reachable from
    needs_verification), or hand-editing the task-queue.md/OPEN_TASKS.md projections
    (render-tier1-state.py regenerates them). Negated/explanatory mentions are exempt."""
    import glob
    hits = []
    for pat in _DOC_TRUTH_GLOBS:
        for path in glob.glob(os.path.join(REPO, pat), recursive=True):
            try:
                with open(path, encoding="utf-8") as f:
                    lines = f.readlines()
            except (OSError, UnicodeDecodeError):
                continue
            in_fence = fence_exempt = False
            for i, line in enumerate(lines, 1):
                if line.lstrip().startswith("```"):
                    if not in_fence:  # opening: is the prose block directly above exempt?
                        j = i - 2                       # line just above the fence (0-based)
                        while j >= 0 and not lines[j].strip():   # skip one blank gap
                            j -= 1
                        frame = []                       # contiguous non-blank prose block
                        while j >= 0 and lines[j].strip():
                            frame.append(lines[j]); j -= 1
                        fence_exempt = bool(_DOC_TRUTH_EXEMPT.search("".join(frame)))
                    in_fence = not in_fence
                    continue
                if _DOC_TRUTH_EXEMPT.search(line):
                    continue
                # A banned pattern echoed inside a code fence is a reference EXAMPLE, not an
                # instruction, when the framing prose above the fence marks the surface
                # read-only / auto-rendered (e.g. the rendered board-line shape). Bare prose
                # teaching the op is never fence-exempt, so seeded drift still fires.
                if in_fence and fence_exempt:
                    continue
                for label, rx in _DOC_TRUTH_BANNED:
                    if rx.search(line):
                        hits.append({"file": os.path.relpath(path, REPO), "line": i,
                                     "kind": label, "text": line.strip()[:120]})
    status = ALERT if hits else PASS
    return {"name": "doc-truth", "status": status, "score": 0 if hits else 1,
            "threshold": "0 protocol-doc drift lines",
            "detail": (f"{len(hits)} protocol-doc drift line(s) — docs teach a forbidden op"
                       if hits else "protocol docs match the governed contract"),
            "samples": hits[:8]}


def meter_front_door_phone_path(recs):
    """Front-door phone-path regression probe (#527).

    The access-token gate regressed TWICE after being 'fixed' with NOTHING exercising the
    real phone path, so Ant found each regression himself ('i thought we fixed that') —
    each one a wasted mobile round-trip that erodes trust in done-claims. This synthetically
    walks the path a phone actually takes and alerts BEFORE he hits it:

      1. Functional — the Caddy front door must VOUCH: a no-cookie request returns the
         console (200), not the token prompt (401) and not a dead door (000/5xx). Also
         asserts the cockpit gate is still active on bare loopback and the upstreams are
         closed on the tailnet IP. Delegated to the canonical check-metis-front-door-gated.sh
         so the assertions never drift from the real regression check.
      2. Config canary — the Caddyfile still injects `header_up x-metis-front-door` (the
         vouch mechanism). This request header is invisible from the client, so the config
         line is the earliest signal that vouching is about to break.
      3. Preview door — the :3750 preview door answers (Caddy route up), so the Studio
         live-preview path a phone uses isn't dark.

    <<MACHINE_1_ID>>-only (the doors + upstreams live here); <<MACHINE_2_ID>> PASSes (it reaches them remotely).
    """
    import socket as _socket
    user = os.environ.get("USER") or ""
    host = (_socket.gethostname() or "").lower()
    if not (user == "Ant" or "<<MACHINE_1_ID>>" in host):
        return {"name": "front-door-phone-path", "status": PASS, "score": 1,
                "threshold": "<<MACHINE_1_ID>>-only meter (front door lives on <<MACHINE_1_ID>>)",
                "detail": "skipped on <<MACHINE_2_ID>>", "samples": []}

    fails, samples = [], []

    # 1. Functional vouch + gate + closed-upstreams (the real regression check).
    try:
        r = subprocess.run(["bash", os.path.join(REPO, "scripts/check-metis-front-door-gated.sh")],
                           capture_output=True, text=True, timeout=30)
        if r.returncode != 0:
            msg = (r.stderr or r.stdout).strip().splitlines()[-1] if (r.stderr or r.stdout).strip() else "check failed"
            fails.append(f"vouch/gate: {msg[:140]}")
        else:
            samples.append("door vouches (200 no-cookie), gate active, upstreams closed")
    except Exception as e:
        fails.append(f"vouch/gate probe error: {e}")

    # 2. Config canary: the vouch header injection is still in the Caddyfile.
    try:
        with open(os.path.join(REPO, "scripts/caddy/Caddyfile")) as f:
            if not re.search(r"header_up\s+x-metis-front-door", f.read()):
                fails.append("Caddyfile no longer injects x-metis-front-door — vouch mechanism removed")
            else:
                samples.append("Caddyfile vouch header present")
    except Exception as e:
        fails.append(f"Caddyfile canary error: {e}")

    # 3. Preview door :3750 answers (Caddy route up; any HTTP code beats a dead port).
    # gethostname() is 'AntFox-Macbook.local' → take the first label for the tailnet FQDN.
    tailnet_host = f"{(host.split('.')[0] or '<<MACHINE_1_HOSTNAME>>')}.tailbe5cff.ts.net"
    try:
        out = subprocess.run(
            ["curl", "-sS", "--max-time", "6", "-o", "/dev/null", "-w", "%{http_code}",
             f"http://{tailnet_host}:3750/"],
            capture_output=True, text=True, timeout=10).stdout.strip()
        if out in ("", "000"):
            fails.append(f"preview door :3750 unreachable (curl code {out or 'none'})")
        else:
            samples.append(f"preview door :3750 answers ({out})")
    except Exception as e:
        fails.append(f"preview door probe error: {e}")

    status = ALERT if fails else PASS
    return {"name": "front-door-phone-path", "status": status, "score": 0 if fails else 1,
            "threshold": "door vouches (200 no-token) + Caddyfile vouch header + :3750 answers",
            "detail": ("; ".join(fails) if fails
                       else "phone path healthy: door vouches, vouch header present, preview door up"),
            "actions": (["check METIS_COMMAND_TOKEN in the Caddy env + restart Caddy; "
                         "verify scripts/caddy/Caddyfile header_up x-metis-front-door"] if fails else []),
            "samples": samples[:3]}


METERS = [meter_signoff, meter_taxonomy, meter_notion_domain_vocab, meter_inbox_quality,
          meter_curator_format,
          meter_headless_model_pin, meter_whisper_stt, meter_kokoro_tts, meter_web_brain_reachable,
          meter_doc_truth, meter_front_door_phone_path]


# ───────────────────────────────── main ──────────────────────────────────────

def _now():
    return datetime.datetime.now().isoformat(timespec="seconds")


def sync_worklist(agent_findings, apply):
    """Maintain the self-heal worklist (the agent-tier backlog the next session works).

    Upsert one entry per current agent-tier finding (keyed by check name; refresh
    last_seen + occurrences + latest actions), and AUTO-CLEAR entries whose check is
    no longer failing (the heal landed or the drift cleared). Returns the open list.
    Skips the write in dry-run so tests don't mutate state.
    """
    try:
        existing = {e["key"]: e for e in json.load(open(WORKLIST)).get("items", [])}
    except Exception:
        existing = {}
    current_keys = {f["name"] for f in agent_findings}
    now = _now()
    items = []
    for f in agent_findings:
        k = f["name"]
        prev = existing.get(k)
        items.append({
            "key": k,
            "title": f["detail"],
            "tier": AGENT,
            "actions": f.get("actions", []),
            "first_seen": prev["first_seen"] if prev else now,
            "last_seen": now,
            "occurrences": (prev["occurrences"] + 1) if prev else 1,
        })
    # entries not in current findings are resolved → dropped (auto-clear)
    cleared = [k for k in existing if k not in current_keys]
    if apply:
        try:
            os.makedirs(os.path.dirname(WORKLIST), exist_ok=True)
            json.dump({"updatedAt": now, "items": items}, open(WORKLIST, "w"), indent=2)
        except Exception:
            pass
    return items, cleared


def _meter_actions(m):
    """Build worklist action strings from a meter's samples. Samples are
    meter-specific: signoff-compliance emits dicts ({session, tail, ...}); the
    taxonomy / inbox-quality / arbiter-format meters emit plain strings. Format by
    shape so one string-sample meter can't crash the whole harness (the prior code
    assumed every sample was a signoff dict and died on the first non-signoff ALERT)."""
    acts = []
    for s in m.get("samples", []):
        if isinstance(s, dict):
            sess = s.get("session", "?")
            tail = (s.get("tail", "") or "")[-120:]
            acts.append(f"FP-candidate {sess}: tune gate regex — tail `{tail}`")
        else:
            acts.append(str(s))
    return acts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="perform safe auto-heals")
    ap.add_argument("--dry-run", action="store_true", help="report only (default)")
    ap.add_argument("--json", action="store_true", help="machine-readable JSON only")
    args = ap.parse_args()
    apply = args.apply and not args.dry_run

    heals = [run_check(fn, apply) for fn in HEALS + load_command_checks()]
    recs = _load_gate_log(24)
    meters = [run_check(lambda a, fn=fn: fn(recs), apply) for fn in METERS]

    healed = [h for h in heals if h["status"] == HEALED]
    # Findings that need someone to act = NEEDS_HUMAN heals + ALERT meters.
    findings = [dict(h, kind="heal") for h in heals if h["status"] == NEEDS_HUMAN] \
             + [dict(m, kind="meter", detail=m["detail"], actions=_meter_actions(m))
                for m in meters if m["status"] == ALERT]

    # Tier each finding; partition.
    for f in findings:
        f.setdefault("escalation", DEFAULT_TIER)
    ant_escalations = [f for f in findings if f["escalation"] == ANT]
    agent_findings = [f for f in findings if f["escalation"] == AGENT]

    worklist, cleared = sync_worklist(agent_findings, apply)

    result = {
        "ts": _now(), "repo": REPO, "applied": apply,
        "heals": heals, "meters": meters,
        "ant_escalations": [{"name": f["name"], "detail": f["detail"],
                             "recommendation": f.get("recommendation",
                                 f"Recommend: review {f['name']}. " + "; ".join(f.get("actions", [])))}
                            for f in ant_escalations],
        "worklist_open": len(worklist),
        "worklist_cleared": cleared,
        "counts": {"healed": len(healed), "ant_escalations": len(ant_escalations),
                   "worklist_open": len(worklist), "cleared": len(cleared)},
    }
    print(json.dumps(result, indent=2))
    if not args.json:
        tag = "APPLY" if apply else "DRY-RUN"
        print(f"[self-heal {tag}] healed={len(healed)} ant_escalations={len(ant_escalations)} "
              f"worklist_open={len(worklist)} cleared={len(cleared)}", file=sys.stderr)
    # Exit non-zero ONLY when Ant must decide — the wrapper gates the @Ant ping on this.
    sys.exit(1 if ant_escalations else 0)


if __name__ == "__main__":
    main()
