#!/usr/bin/env python3
"""self-heal.py — daily deterministic self-heal + compliance metering.

Two layers, complementing the LLM `system-audit.sh` (which is semantic + report-only):

  LAYER A — mechanical heal: cheap deterministic plumbing checks. AUTO-FIX only the
    safe, idempotent, reversible class (broken symlinks, non-exec hooks); everything
    judgment-laden (config drift that could regress newer live state, stray .git
    dirs) is REPORTED, never blind-applied (feedback_validate_heal_commands).

  LAYER B — compliance meters: a pluggable registry that *counts adherence* to
    standards that have a measurable signal, and alerts below threshold. This is the
    generalizable answer to "catch stuff like the 2% sign-off gap more broadly":
    a standard isn't trusted because it exists, it's trusted because a meter measures
    it. Adding a meter is one function appended to METERS.

Output: a JSON result to stdout (the .sh wrapper renders markdown + Discord digest).
Portable: derives repo root from this file; no hardcoded per-machine paths.

Run modes:
  --dry-run   report what WOULD heal, change nothing (default for tests)
  --apply     perform the safe auto-heals (default for the scheduled run)
  --json      emit machine-readable JSON only (no human summary on stderr)
"""
import argparse, json, os, re, subprocess, sys, glob, datetime

REPO = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))
HOME = os.path.expanduser("~")
GATE_LOG = os.path.join(HOME, ".openclaw", "logs", "signoff-gate.jsonl")
# Repo-tracked registry of bug-derived command checks (added via add-healthcheck.py).
# Each fix that's mechanically detectable registers one entry here, so the harness
# grows itself — no python editing, and it syncs to every machine.
HEALTH_CHECKS_FILE = os.path.join(REPO, "docs", "process", "state", "health-checks.json")
# Machine-local runtime state (each machine self-heals its own plumbing) — NOT in the
# repo, to avoid cross-machine churn/conflicts. Regenerated by every self-heal run.
WORKLIST = os.path.join(HOME, ".openclaw", "self-heal-worklist.json")

OK, HEALED, NEEDS_HUMAN = "OK", "HEALED", "NEEDS_HUMAN"
PASS, ALERT = "PASS", "ALERT"

# Escalation tiers (per agent-escalation-thresholds.md):
#   auto  → fixed silently, no human, no record beyond the report
#   agent → a session must act, but it is NOT an Ant decision → self-heal worklist
#           (consumed by the next Jay session; never pinged to Ant)
#   ant   → trips the escalation bar (money / irreversible-high-cost / external /
#           secrets / destructive-ambiguous) → @Ant decide-and-present ping
AUTO, AGENT, ANT = "auto", "agent", "ant"

# Per-finding tier. Default for a needs-action finding is AGENT — Ant is pinged ONLY
# when a check explicitly returns escalation=ANT (none do today; the tier is reserved
# for findings that genuinely match the bar, e.g. a future leaked-secret meter).
DEFAULT_TIER = AGENT


def sh(cmd, timeout=60):
    # METIS_PYTHON pins children to the interpreter running this harness. Needed
    # because command-checks run under `bash -lc`, whose /etc/profile rebuilds
    # PATH (Ant's real PATH lives in zsh files bash never sources) and resolves
    # python3 to a yaml-less /usr/local/bin install — the taxonomy meter died
    # under it (found 2026-06-11). An env var survives profile sourcing; PATH
    # does not.
    env = dict(os.environ, METIS_PYTHON=sys.executable)
    try:
        p = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=timeout, env=env)
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    except Exception as e:
        return 1, str(e)


# ───────────────────────── LAYER A — mechanical heal ─────────────────────────

def heal_symlinks(apply):
    """Re-link any ~/.claude symlink declared in mirror-manifest.json that is
    broken/missing/wrong. Pure plumbing, fully reversible → safe to auto-heal."""
    manifest = os.path.join(REPO, "ClaudeCode", "mirror-manifest.json")
    actions, bad = [], 0
    try:
        m = json.load(open(manifest))
    except Exception as e:
        return {"name": "symlinks", "status": NEEDS_HUMAN,
                "detail": f"cannot read mirror-manifest.json: {e}", "actions": []}
    for entry in m.get("symlinks", []):
        link = os.path.expanduser(entry["link"])
        want = os.path.join(REPO, entry["target"])
        cur = os.path.realpath(link) if os.path.lexists(link) else None
        if cur == os.path.realpath(want):
            continue
        bad += 1
        if apply:
            try:
                if os.path.lexists(link):
                    os.remove(link)
                os.makedirs(os.path.dirname(link), exist_ok=True)
                os.symlink(want, link)
                actions.append(f"relinked {entry['link']} → {entry['target']}")
            except Exception as e:
                actions.append(f"FAILED relink {entry['link']}: {e}")
        else:
            actions.append(f"would relink {entry['link']} → {entry['target']}")
    if bad == 0:
        return {"name": "symlinks", "status": OK, "detail": "all manifest symlinks intact", "actions": []}
    status = HEALED if apply and all("FAILED" not in a for a in actions) else NEEDS_HUMAN
    return {"name": "symlinks", "status": status, "detail": f"{bad} symlink(s) off", "actions": actions}


def heal_hook_exec(apply):
    """Ensure every hook/bin script is executable. Lost +x silently disables a hook."""
    actions = []
    for pat in ("ClaudeCode/hooks/*.sh", "ClaudeCode/bin/*.sh", "scripts/*.sh"):
        for f in glob.glob(os.path.join(REPO, pat)):
            if not os.access(f, os.X_OK):
                rel = os.path.relpath(f, REPO)
                if apply:
                    try:
                        os.chmod(f, os.stat(f).st_mode | 0o111)
                        actions.append(f"chmod +x {rel}")
                    except Exception as e:
                        actions.append(f"FAILED chmod {rel}: {e}")
                else:
                    actions.append(f"would chmod +x {rel}")
    if not actions:
        return {"name": "hook-exec", "status": OK, "detail": "all scripts executable", "actions": []}
    status = HEALED if apply and all("FAILED" not in a for a in actions) else NEEDS_HUMAN
    return {"name": "hook-exec", "status": status, "detail": f"{len(actions)} non-exec script(s)", "actions": actions}


def check_hook_wiring(apply):
    """Verify every ClaudeCode/hooks/*.sh referenced from settings.json is actually
    wired. REPORT only — editing settings.json is a judgment call (localKeys merge)."""
    settings = os.path.join(HOME, ".claude", "settings.json")
    try:
        blob = open(settings).read()
    except Exception as e:
        return {"name": "hook-wiring", "status": NEEDS_HUMAN, "detail": f"no settings.json: {e}", "actions": []}
    # Hooks that MUST be wired (the enforcement/identity set).
    required = ["hook-signoff-gate.sh", "hook-alerts.sh", "hook-session-init.sh",
                "hook-prompt-guard.sh"]
    missing = [h for h in required if h not in blob]
    if not missing:
        return {"name": "hook-wiring", "status": OK, "detail": "required hooks wired", "actions": []}
    return {"name": "hook-wiring", "status": NEEDS_HUMAN,
            "detail": f"settings.json missing: {', '.join(missing)}",
            "actions": [f"add {h} to the matching hooks array in ~/.claude/settings.json" for h in missing]}


def check_mirror_drift(apply):
    """Config drift Jay-vs-canonical. REPORT only — mirror apply is canonical→live and
    can regress newer live state (feedback_validate_heal_commands)."""
    rc, out = sh(["python3", os.path.join(REPO, "scripts", "mirror.py"), "check"])
    clean = (rc == 0 and "in sync" in out.lower())
    if clean:
        return {"name": "mirror-drift", "status": OK, "detail": "Jay in sync with canonical", "actions": []}
    return {"name": "mirror-drift", "status": NEEDS_HUMAN, "detail": "mirror drift detected",
            "actions": ["review: python3 scripts/mirror.py check  (apply only after confirming live isn't newer)"]}


def check_stray_git(apply):
    """Nested .git dirs under projects/ cause wrong-dir writes / silent git failures —
    but ONLY when the outer repo doesn't ignore them. A gitignored nested repo (e.g.
    projects/polymarket-bot, a deliberate public/private carveout with its own remotes)
    is intentional and invisible to outer-repo git ops, so it's NOT a stray. Flag only
    nested .git dirs the outer repo does NOT ignore."""
    rc, out = sh(["bash", "-lc", f"find '{REPO}/projects' -name .git -maxdepth 3 2>/dev/null"])
    strays = []
    for line in out.splitlines():
        d = line.strip()
        if not d:
            continue
        rel = os.path.relpath(d, REPO)
        # outer repo ignores it → deliberate separate repo, not a stray
        ig, _ = sh(["bash", "-lc", f"git -C '{REPO}' check-ignore -q '{rel}'"])
        if ig != 0:
            strays.append(rel)
    if not strays:
        return {"name": "stray-git", "status": OK, "detail": "no un-ignored nested .git under projects/", "actions": []}
    return {"name": "stray-git", "status": NEEDS_HUMAN,
            "detail": f"{len(strays)} un-ignored nested .git dir(s)",
            "actions": [f"investigate {r} — gitignore it (if intentional) or register as submodule" for r in strays]}


def check_gitsync_drift(apply):
    """Live git-sync script vs canonical + heartbeat (the 2026-05-30 corruption class).
    Detection only — which side is canonical is a judgment call → agent worklist."""
    rc, out = sh(["bash", os.path.join(REPO, "scripts", "check-sync-drift.sh")])
    if rc == 0:
        return {"name": "gitsync-drift", "status": OK, "detail": "live git-sync matches canonical + healthy", "actions": []}
    lines = [l.strip() for l in out.splitlines() if l.strip() and not l.startswith("OK")]
    return {"name": "gitsync-drift", "status": NEEDS_HUMAN,
            "detail": "git-sync script drift or stale heartbeat",
            "actions": lines[:4] or ["run scripts/check-sync-drift.sh and review"]}


def heal_autosync(apply):
    """Auto-sync daemon liveness (#101 — daemon found fully UNLOADED, deferred commits
    stranded). Read-only in dry-run; in apply mode delegates the reload to the proven
    ensure-autosync-loaded.sh (which self-alerts on failure)."""
    label = "ant.openclaw-git-sync"
    plist = os.path.join(HOME, "Library", "LaunchAgents", f"{label}.plist")
    rc, out = sh(["bash", "-lc", f"launchctl list 2>/dev/null | grep -q {label}"])
    loaded = (rc == 0)
    if loaded:
        return {"name": "autosync-daemon", "status": OK, "detail": "daemon loaded", "actions": []}
    if not os.path.exists(plist):
        return {"name": "autosync-daemon", "status": OK, "detail": "daemon not installed on this machine", "actions": []}
    if apply:
        r2, o2 = sh(["bash", os.path.join(REPO, "scripts", "ensure-autosync-loaded.sh")])
        if "reload FAILED" in o2 or "RELOAD FAILED" in o2:
            return {"name": "autosync-daemon", "status": NEEDS_HUMAN, "detail": "daemon unloaded; reload FAILED",
                    "actions": [f"reload manually: launchctl load -w {plist}"]}
        return {"name": "autosync-daemon", "status": HEALED, "detail": "daemon was unloaded — reloaded", "actions": ["reloaded ant.openclaw-git-sync"]}
    return {"name": "autosync-daemon", "status": NEEDS_HUMAN, "detail": "daemon UNLOADED (deferred commits will strand)",
            "actions": [f"reload: launchctl load -w {plist}"]}


def check_lane_bloat(apply):
    """Lane sessions over the 20k-token bloat line → cold-start cascade. Detection only;
    a reset can clobber an in-flight lane call, so it's agent-tier, not auto."""
    bloated = []
    for lane in ("forge", "scout", "shield", "echo", "curator"):
        p = os.path.join(HOME, ".openclaw", "agents", lane, "sessions", "sessions.json")
        if not os.path.exists(p):
            continue
        try:
            d = json.load(open(p))
            tok = int(d.get(f"agent:{lane}:main", {}).get("inputTokens") or 0)
            if tok > 20_000:
                bloated.append(f"{lane}:{tok:,}")
        except Exception:
            pass
    if not bloated:
        return {"name": "lane-bloat", "status": OK, "detail": "no lane over 20k tokens", "actions": []}
    return {"name": "lane-bloat", "status": NEEDS_HUMAN, "detail": "bloated lane(s): " + ", ".join(bloated),
            "actions": ["run: lane-health --reset-bloated"]}


_RECON = {}
def _reconcile_lines():
    if "lines" not in _RECON:
        rc, out = sh(["python3", os.path.join(REPO, "scripts", "agent-work.py"), "reconcile"])
        _RECON["lines"] = [l.strip() for l in out.splitlines() if re.match(r"(WARN|FAIL)\s+I\d", l.strip())]
    return _RECON["lines"]


def _invariant_finding(name, codes, label):
    pat = re.compile(r"\bI(" + "|".join(str(c) for c in codes) + r")\b")
    hits = [l for l in _reconcile_lines() if pat.search(l)]
    if not hits:
        return {"name": name, "status": OK, "detail": f"no {label} invariant violations", "actions": []}
    fails = [h for h in hits if h.startswith("FAIL")]
    status = NEEDS_HUMAN  # both FAIL and WARN go to the agent worklist; bar-tripping is ant-tier (none here)
    return {"name": name, "status": status,
            "detail": f"{len(hits)} {label} drift item(s) ({len(fails)} fail)",
            "actions": [h[:160] for h in hits[:5]] + ["reconcile via scripts/agent-work.py + correct-state"]}


def check_lease_invariants(apply):
    """Lease/checkout/fence drift (I5/I6) — the active-checkouts conflict-loop class."""
    return _invariant_finding("lease-drift", [5, 6], "lease")


def check_taskstate_drift(apply):
    """Task-state ↔ projection ↔ working-context drift (I4/I7/I8)."""
    return _invariant_finding("taskstate-drift", [4, 7, 8], "task-state")


def check_dashboard_contract(apply):
    """Dashboard /api/all field contract (detail.js silent-break class). Detection only;
    a restart is heavier than a daily heal should blind-fire, so agent-tier."""
    rc, out = sh(["bash", os.path.join(REPO, "scripts", "smoke-api-all.sh")], timeout=60)
    if rc == 0:
        return {"name": "dashboard-contract", "status": OK, "detail": "/api/all contract OK", "actions": []}
    last = [l.strip() for l in out.splitlines() if "FAIL" in l or "unreachable" in l][-2:]
    return {"name": "dashboard-contract", "status": NEEDS_HUMAN, "detail": "/api/all contract broken or dashboard down",
            "actions": last + ["investigate; if down: bash scripts/restart-dashboard.sh"]}


def check_detector_gaps(apply):
    """Surface bugs recorded (via add-healthcheck.py --gap) as not-yet-mechanically-
    detectable, so 'we'll add a detector later' doesn't vanish — it stays on the worklist
    until someone writes the check or confirms it's obsolete."""
    try:
        gaps = json.load(open(HEALTH_CHECKS_FILE)).get("gaps", [])
    except Exception:
        gaps = []
    if not gaps:
        return {"name": "detector-gaps", "status": OK, "detail": "no open detector gaps", "actions": []}
    return {"name": "detector-gaps", "status": NEEDS_HUMAN,
            "detail": f"{len(gaps)} bug(s) without a mechanical detector",
            "actions": [f"{g['name']}: {g.get('reason','')} — write a check or close the gap" for g in gaps[:5]]}


HEALS = [heal_symlinks, heal_hook_exec, check_hook_wiring, check_mirror_drift, check_stray_git,
         check_gitsync_drift, heal_autosync, check_lane_bloat,
         check_lease_invariants, check_taskstate_drift, check_dashboard_contract,
         check_detector_gaps]


# ──────────── declarative command-checks (the self-growing registry) ───────────

def _make_command_check(spec):
    """Turn a health-checks.json entry into a check fn. A command-check passes when its
    cmd exits ok_exit; otherwise it's a finding at the spec's tier (default agent)."""
    ok_exit = int(spec.get("ok_exit", 0))
    timeout = int(spec.get("timeout", 60))

    def _check(apply):
        rc, out = sh(["bash", "-lc", spec["cmd"]], timeout=timeout)
        if rc == ok_exit:
            return {"name": spec["name"], "status": OK,
                    "detail": spec.get("ok_detail", f"{spec['name']} ok"), "actions": []}
        ref = f" (regresses {spec['bug_ref']})" if spec.get("bug_ref") else ""
        # Optional declarative self-heal: in apply mode, run heal_cmd and re-check.
        if apply and spec.get("heal_cmd"):
            sh(["bash", "-lc", spec["heal_cmd"]], timeout=timeout)
            rc2, _ = sh(["bash", "-lc", spec["cmd"]], timeout=timeout)
            if rc2 == ok_exit:
                return {"name": spec["name"], "status": HEALED,
                        "detail": spec.get("fail_detail", spec["name"]) + ref + " — auto-healed",
                        "actions": [f"ran heal: {spec['heal_cmd']}"]}
        tail = [l.strip() for l in out.splitlines() if l.strip()][-3:]
        return {"name": spec["name"], "status": NEEDS_HUMAN,
                "detail": spec.get("fail_detail", f"{spec['name']} check failed") + ref,
                "actions": tail + list(spec.get("actions", [])),
                "escalation": spec.get("tier", AGENT)}
    _check.__name__ = "cmd_" + re.sub(r"[^0-9a-zA-Z]+", "_", spec["name"])
    return _check


def load_command_checks():
    try:
        specs = json.load(open(HEALTH_CHECKS_FILE)).get("checks", [])
    except Exception:
        return []
    out = []
    for s in specs:
        if isinstance(s, dict) and s.get("name") and s.get("cmd") and not s.get("disabled"):
            out.append(_make_command_check(s))
    return out


def run_check(fn, apply):
    """Fault-isolate a single check: a check that throws or returns a bad shape becomes a
    NEEDS_HUMAN finding about itself, never killing the whole run (a blind spot is worse
    than a noisy one)."""
    try:
        r = fn(apply)
        if not isinstance(r, dict) or "name" not in r or "status" not in r:
            raise ValueError(f"bad result shape: {r!r}")
        r.setdefault("detail", "")
        r.setdefault("actions", [])
        return r
    except Exception as e:
        return {"name": getattr(fn, "__name__", "unknown-check"), "status": NEEDS_HUMAN,
                "detail": f"CHECK ERRORED: {e}", "escalation": AGENT,
                "actions": ["a broken check is a blind spot — fix the check fn/spec"]}


# ───────────────────────── LAYER B — compliance meters ───────────────────────

def _load_gate_log(hours=24):
    if not os.path.exists(GATE_LOG):
        return []
    cutoff = datetime.datetime.now() - datetime.timedelta(hours=hours)
    out = []
    for line in open(GATE_LOG):
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
            ts = datetime.datetime.fromisoformat(r.get("ts", ""))
        except Exception:
            continue
        if ts >= cutoff:
            out.append(r)
    return out


def meter_signoff(recs):
    """Sign-off standard adherence + false-positive surfacing (the FP loop).

    - block_rate: share of stops the gate had to intervene on (trend; high = the
      model still isn't emitting the block inline).
    - fp_candidates: blocks whose closing text already LOOKED like a sign-off the
      regex rejected (header present but fields didn't match, or ≥2 field words in
      the tail). These are exactly the cases that need a regex tweak — surfaced with
      their tails so the fix is a copy-paste, never auto-applied.
    """
    g = [r for r in recs if r.get("session") and r.get("decision")]
    total = len(g)
    blocks = [r for r in g if r["decision"] == "block"]
    # A TRUE false-positive candidate = a block where the FULL sign-off shape was
    # plausibly present but a gate regex rejected it. Two shapes qualify:
    #   1. header matched but fields didn't → field-regex miss candidate;
    #   2. field labels present AND a header-LIKE bold line (`**…** — …`) in the
    #      tail → header-regex miss candidate.
    # Field words ALONE are not enough: a stop ending `- Next: …` with no header at
    # all is genuine non-compliance (the 07fd0e09 class, reviewed 2026-06-11) and
    # belongs in the block_rate trend, not a daily FP ALERT. (A bare header match is
    # likewise too loose: stray bold-with-separator prose like `**Read + Insert**`.)
    fieldword = re.compile(r"\b(Done|Verified|Check|Next|Asks)\b\s*:", re.I)
    # Line-anchored: a real header opens its own line; mid-sentence bolds like
    # "My lean: **build the bridge** — it's…" must not qualify.
    headerlike = re.compile(r"^\s*\*\*[^*\n]+\*\*\s*(?:—|--)\s*\S", re.M)
    # Either way the MISSING half must look present to a looser regex — h=T alone
    # is a stray prose bold (0a111d59: `**Action required…**` in a shield verdict),
    # f-words alone are a fieldless prose mention.
    fp = []
    for b in blocks:
        tail = b.get("tail", "")
        if b.get("header_match") and not b.get("fields_match") and fieldword.search(tail):
            fp.append(b)
        elif b.get("fields_match") and not b.get("header_match") and headerlike.search(tail):
            fp.append(b)
    block_rate = (len(blocks) / total) if total else 0.0
    # ALERT if any false-positive candidate (regex needs tuning) — the headline ask.
    status = ALERT if fp else PASS
    detail = f"{total} stops/24h · {len(blocks)} blocked ({block_rate:.0%}) · {len(fp)} FP-candidate(s)"
    samples = [{"session": b.get("session", "")[:8],
                "header_match": b.get("header_match"), "fields_match": b.get("fields_match"),
                "tail": b.get("tail", "")[-200:]} for b in fp[:5]]
    return {"name": "signoff-compliance", "status": status, "score": round(1 - block_rate, 3),
            "threshold": "0 FP-candidates", "detail": detail, "samples": samples}


def meter_taxonomy(recs):
    """Drift between tasks.json and the canonical taxonomy SoT (docs/process/taxonomy.yaml):
    off-vocab domain/status or a project with no domain mapping. 0 = clean.

    The taxonomy validator + its SoT are an OPTIONAL overlay (the vocab is
    org/personal-specific; a portable consumer may not ship one). A missing file
    must SKIP this meter, not crash the whole self-heal harness — so guard both the
    validator script and the SoT, and fail soft on any load/scan error."""
    import importlib.util
    lint_path = os.path.join(REPO, "scripts", "taxonomy-lint.py")
    sot_path = os.path.join(REPO, "docs/process", "taxonomy.yaml")
    skip = {"name": "taxonomy-drift", "status": PASS, "score": 1,
            "threshold": "0 off-vocab", "detail": "taxonomy SoT/validator absent — skipped", "samples": []}
    if not (os.path.exists(lint_path) and os.path.exists(sot_path)):
        return skip
    try:
        spec = importlib.util.spec_from_file_location("taxonomy_lint", lint_path)
        tx = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(tx)
        findings = tx._scan_tasks()
    except Exception as e:
        return {**skip, "detail": f"taxonomy lint unavailable — skipped ({e})"}
    status = ALERT if findings else PASS
    return {"name": "taxonomy-drift", "status": status, "score": 0 if findings else 1,
            "threshold": "0 off-vocab", "detail": f"{len(findings)} taxonomy drift finding(s) vs canonical vocab",
            "samples": findings[:5]}


def meter_inbox_quality(recs):
    """Thin Ant-decisions (#326-A safety-net): an owner=ant decision-point that is
    open + undecided but LACKS the structured fields #323 needs to render a clean
    one-tap card — decisionOptions, recommendation, or decisionContext. Without
    them it regresses to a crude regex Yes/No card in the inbox. 0 = every genuine
    Ant-decision is properly structured.

    Detective only — flags thin decisions for enrichment, never blocks authoring.
    Fails soft if the task store is absent/unreadable (a portable consumer may not
    ship one), matching meter_taxonomy's optional-overlay contract."""
    tasks_path = os.path.join(REPO, "docs/process/state/tasks.json")
    skip = {"name": "inbox-quality", "status": PASS, "score": 1,
            "threshold": "0 thin Ant-decisions",
            "detail": "task store absent — skipped", "samples": []}
    if not os.path.exists(tasks_path):
        return skip
    try:
        d = json.load(open(tasks_path))
        ts = d.get("tasks", d)
        ts = list(ts.values()) if isinstance(ts, dict) else ts
    except Exception as e:
        return {**skip, "detail": f"task store unreadable — skipped ({e})"}
    TERMINAL = {"done", "cancelled", "archived"}
    thin = []
    for t in ts:
        if t.get("state") in TERMINAL:
            continue
        if (t.get("owner") or "").strip().lower() != "ant":
            continue
        if (t.get("decision") or "").strip():
            continue  # already decided — the point is closed
        ndp = (t.get("nextDecisionPoint") or "").strip()
        is_decision = (bool(ndp) and not re.match(r"none\b", ndp, re.I)) or bool(t.get("decisionOptions"))
        if not is_decision:
            continue
        missing = [f for f in ("decisionOptions", "recommendation", "decisionContext") if not t.get(f)]
        if missing:
            thin.append(f"{t.get('taskId')} missing {','.join(missing)}")
    status = ALERT if thin else PASS
    return {"name": "inbox-quality", "status": status, "score": 0 if thin else 1,
            "threshold": "0 thin Ant-decisions",
            "detail": f"{len(thin)} owner=ant decision(s) lacking structured #323 fields",
            "samples": thin[:5]}


def meter_curator_format(recs):
    """Curator JSON discipline (#333): count 'Curator returned invalid JSON' /
    'no JSON object' lines in the queue-runner log from the last 24h. Lanes
    imitate formats present in reviewed content (the sign-off-block leak found
    2026-06-12: shield/curator answered in block format after reviewing the
    self-heal audit doc, which quotes meter_signoff patterns), and a malformed
    curator verdict silently degrades the quality gate to a retry. #332's
    raw_decode tolerates trailing prose; this catches the cases it can't.
    Fails soft when the log is absent (runner not installed here)."""
    import time as _time
    log_path = os.path.expanduser("~/.openclaw/logs/queue-runner.log")
    skip = {"name": "curator-format", "status": PASS, "score": 1,
            "threshold": "0 parse failures/24h",
            "detail": "queue-runner log absent — skipped", "samples": []}
    if not os.path.exists(log_path):
        return skip
    try:
        if os.path.getmtime(log_path) < _time.time() - 24 * 3600:
            return {**skip, "detail": "queue-runner log stale (>24h) — skipped"}
        bad = []
        with open(log_path, errors="replace") as f:
            for line in f.readlines()[-4000:]:
                if "Curator returned invalid JSON" in line or "Curator returned no JSON object" in line:
                    bad.append(line.strip()[:160])
    except Exception as e:
        return {**skip, "detail": f"queue-runner log unreadable — skipped ({e})"}
    status = ALERT if bad else PASS
    return {"name": "curator-format", "status": status, "score": 0 if bad else 1,
            "threshold": "0 parse failures/24h",
            "detail": f"{len(bad)} curator JSON parse failure(s) in recent runner log",
            "samples": bad[-5:]}


METERS = [meter_signoff, meter_taxonomy, meter_inbox_quality, meter_curator_format]


# ───────────────────────────────── main ──────────────────────────────────────

def _now():
    return datetime.datetime.now().isoformat(timespec="seconds")


def sync_worklist(agent_findings, apply):
    """Maintain the self-heal worklist (the agent-tier backlog the next session works).

    Upsert one entry per current agent-tier finding (keyed by check name; refresh
    last_seen + occurrences + latest actions), and AUTO-CLEAR entries whose check is
    no longer failing (the heal landed or the drift cleared). Returns the open list.
    Skips the write in dry-run so tests don't mutate state.
    """
    try:
        existing = {e["key"]: e for e in json.load(open(WORKLIST)).get("items", [])}
    except Exception:
        existing = {}
    current_keys = {f["name"] for f in agent_findings}
    now = _now()
    items = []
    for f in agent_findings:
        k = f["name"]
        prev = existing.get(k)
        items.append({
            "key": k,
            "title": f["detail"],
            "tier": AGENT,
            "actions": f.get("actions", []),
            "first_seen": prev["first_seen"] if prev else now,
            "last_seen": now,
            "occurrences": (prev["occurrences"] + 1) if prev else 1,
        })
    # entries not in current findings are resolved → dropped (auto-clear)
    cleared = [k for k in existing if k not in current_keys]
    if apply:
        try:
            os.makedirs(os.path.dirname(WORKLIST), exist_ok=True)
            json.dump({"updatedAt": now, "items": items}, open(WORKLIST, "w"), indent=2)
        except Exception:
            pass
    return items, cleared


def _meter_actions(m):
    """Build worklist action strings from a meter's samples. Samples are
    meter-specific: signoff-compliance emits dicts ({session, tail, ...}); the
    taxonomy / inbox-quality / curator-format meters emit plain strings. Format by
    shape so one string-sample meter can't crash the whole harness (the prior code
    assumed every sample was a signoff dict and died on the first non-signoff ALERT)."""
    acts = []
    for s in m.get("samples", []):
        if isinstance(s, dict):
            sess = s.get("session", "?")
            tail = (s.get("tail", "") or "")[-120:]
            acts.append(f"FP-candidate {sess}: tune gate regex — tail `{tail}`")
        else:
            acts.append(str(s))
    return acts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="perform safe auto-heals")
    ap.add_argument("--dry-run", action="store_true", help="report only (default)")
    ap.add_argument("--json", action="store_true", help="machine-readable JSON only")
    args = ap.parse_args()
    apply = args.apply and not args.dry_run

    heals = [run_check(fn, apply) for fn in HEALS + load_command_checks()]
    recs = _load_gate_log(24)
    meters = [run_check(lambda a, fn=fn: fn(recs), apply) for fn in METERS]

    healed = [h for h in heals if h["status"] == HEALED]
    # Findings that need someone to act = NEEDS_HUMAN heals + ALERT meters.
    findings = [dict(h, kind="heal") for h in heals if h["status"] == NEEDS_HUMAN] \
             + [dict(m, kind="meter", detail=m["detail"], actions=_meter_actions(m))
                for m in meters if m["status"] == ALERT]

    # Tier each finding; partition.
    for f in findings:
        f.setdefault("escalation", DEFAULT_TIER)
    ant_escalations = [f for f in findings if f["escalation"] == ANT]
    agent_findings = [f for f in findings if f["escalation"] == AGENT]

    worklist, cleared = sync_worklist(agent_findings, apply)

    result = {
        "ts": _now(), "repo": REPO, "applied": apply,
        "heals": heals, "meters": meters,
        "ant_escalations": [{"name": f["name"], "detail": f["detail"],
                             "recommendation": f.get("recommendation",
                                 f"Recommend: review {f['name']}. " + "; ".join(f.get("actions", [])))}
                            for f in ant_escalations],
        "worklist_open": len(worklist),
        "worklist_cleared": cleared,
        "counts": {"healed": len(healed), "ant_escalations": len(ant_escalations),
                   "worklist_open": len(worklist), "cleared": len(cleared)},
    }
    print(json.dumps(result, indent=2))
    if not args.json:
        tag = "APPLY" if apply else "DRY-RUN"
        print(f"[self-heal {tag}] healed={len(healed)} ant_escalations={len(ant_escalations)} "
              f"worklist_open={len(worklist)} cleared={len(cleared)}", file=sys.stderr)
    # Exit non-zero ONLY when Ant must decide — the wrapper gates the @Ant ping on this.
    sys.exit(1 if ant_escalations else 0)


if __name__ == "__main__":
    main()
