#!/usr/bin/env bash
set -euo pipefail

# self-heal.sh — daily deterministic self-heal + compliance-meter run.
#
# Thin scheduled wrapper around scripts/self-heal.py (the brains). Mirrors the
# system-audit.sh idiom: env-portable, directory-lock, persists a dated report,
# pings Discord ONLY when a human must act (NEEDS_HUMAN heal or meter ALERT).
#
# Complements system-audit.sh: that is the LLM, semantic, report-only pass ("what's
# architecturally wrong"); this is the deterministic, mechanical pass that auto-fixes
# safe plumbing drift and *measures* standard adherence ("is the plumbing intact and
# are the standards actually being followed"). Self-heal runs 08:00, audit 08:30.

export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${REPO:-$(cd "$SCRIPT_DIR/.." && git rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/..")}"
DATE="${DATE:-$(date +%Y-%m-%d)}"
AUDIT_DIR="$REPO/docs/process/audits"
REPORT="$AUDIT_DIR/self-heal-$DATE.md"
LOG_DIR="${LOG_DIR:-$HOME/.openclaw/logs}"
LOG="$LOG_DIR/self-heal.log"
OPENCLAW_JSON="${OPENCLAW_JSON:-$HOME/.openclaw/openclaw.json}"
DISCORD_CHANNEL="${DISCORD_CHANNEL:-1489674856579600455}"
CURL_BIN="${CURL_BIN:-curl}"
# --dry-run by default for manual runs; the LaunchAgent passes --apply.
MODE="${1:---apply}"

mkdir -p "$AUDIT_DIR" "$LOG_DIR"
exec >> "$LOG" 2>&1
echo "=== self-heal starting $(date) (repo=$REPO mode=$MODE) ==="

# --- Concurrency guard: directory lock (flock unavailable in LaunchAgent env) ---
LOCK_DIR=/tmp/self-heal.lock.d
if mkdir "$LOCK_DIR" 2>/dev/null; then
  echo "$$" > "$LOCK_DIR/pid"; trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM
else
  holder=$(cat "$LOCK_DIR/pid" 2>/dev/null || true)
  if [ -n "$holder" ] && kill -0 "$holder" 2>/dev/null; then
    echo "Already running under pid $holder, skipping."; exit 0
  fi
  echo "Reclaiming stale lock."; rm -rf "$LOCK_DIR"
  mkdir "$LOCK_DIR"; echo "$$" > "$LOCK_DIR/pid"; trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM
fi

discord_post() {
  local msg="$1" token
  token=$(python3 -c "import json; d=json.load(open('$OPENCLAW_JSON')); print(d['channels']['discord']['token'])" 2>/dev/null || echo "")
  [ -z "$token" ] && return
  "$CURL_BIN" -s -X POST "https://discord.com/api/v10/channels/$DISCORD_CHANNEL/messages" \
    -H "Authorization: Bot $token" -H "Content-Type: application/json" \
    -d "{\"content\": \"$msg\"}" > /dev/null || true
}

RESULT_JSON=$(mktemp)
set +e
python3 "$REPO/scripts/self-heal.py" "$MODE" --json > "$RESULT_JSON" 2>>"$LOG"
RC=$?
set -e
if [ ! -s "$RESULT_JSON" ]; then
  echo "[ERROR] empty self-heal output"; discord_post "⚠️ self-heal failed — empty output. Check $LOG"; rm -f "$RESULT_JSON"; exit 1
fi

# --- Render the markdown report (MY artifact — never pushed at Ant; consumed by the
#     next session via the worklist + session-init nudge). ---
python3 - "$RESULT_JSON" "$REPORT" "$DATE" <<'PYEOF'
import json, sys
r = json.load(open(sys.argv[1])); report, date = sys.argv[2], sys.argv[3]
c = r["counts"]
L = [f"# Self-Heal Report — {date}",
     f"\n_Generated by scripts/self-heal.sh · applied={r['applied']} · {r['ts']}_\n",
     f"**Healed:** {c['healed']} · **Ant escalations:** {c['ant_escalations']} · "
     f"**Worklist open:** {c['worklist_open']} · **Cleared:** {c['cleared']}\n"]
if r.get("ant_escalations"):
    L.append("## 🛑 Escalated to Ant (decision required)\n")
    for e in r["ant_escalations"]:
        L.append(f"- **{e['name']}** — {e['detail']} · {e['recommendation']}")
    L.append("")
L.append("## Layer A — mechanical heal\n")
for h in r["heals"]:
    icon = {"OK":"✅","HEALED":"🔧","NEEDS_HUMAN":"📋"}.get(h["status"],"•")
    L.append(f"### {icon} {h['name']} — {h['status']}")
    L.append(h["detail"])
    L += [f"- {a}" for a in h.get("actions", [])]
    L.append("")
L.append("## Layer B — compliance meters\n")
for m in r["meters"]:
    icon = "✅" if m["status"]=="PASS" else "📋"
    L.append(f"### {icon} {m['name']} — {m['status']}  (score {m.get('score','-')}, target {m.get('threshold','-')})")
    L.append(m["detail"])
    for s in m.get("samples", []):
        L.append(f"- FP-candidate `{s.get('session','')}` header={s.get('header_match')} "
                 f"fields={s.get('fields_match')} — tail: `{s.get('tail','')[-160:]}`")
    L.append("")
if r.get("worklist_cleared"):
    L.append("## Auto-cleared since last run\n")
    L += [f"- {k}" for k in r["worklist_cleared"]]
    L.append("")
open(report, "w").write("\n".join(L) + "\n")
PYEOF

# --- Routing: Ant sees ONLY genuine decisions (agent-escalation-thresholds.md).
#     Agent-tier findings live in the worklist (next session works them) — NO ping.
#     The all-green / agent-only case is SILENT to Ant by design. ---
ESC=$(python3 -c "import json;print(json.load(open('$RESULT_JSON'))['counts']['ant_escalations'])")
HEALED=$(python3 -c "import json;print(json.load(open('$RESULT_JSON'))['counts']['healed'])")
WL=$(python3 -c "import json;print(json.load(open('$RESULT_JSON'))['counts']['worklist_open'])")

if [ "$ESC" -gt 0 ]; then
  # decide-and-present @Ant ping, one line per escalation
  MSG=$(python3 -c "
import json
r=json.load(open('$RESULT_JSON'))
lines=['🛑 <@Ant> self-heal needs a decision ($DATE):']
for e in r['ant_escalations']:
    lines.append(f\"• {e['detail']} — {e['recommendation']}\")
print('\\\\n'.join(lines))")
  discord_post "$MSG"
  echo "Escalated $ESC item(s) to Ant."
else
  echo "No Ant escalations — silent (healed:$HEALED worklist_open:$WL). Report: $REPORT"
fi
rm -f "$RESULT_JSON"
echo "=== self-heal complete. healed:$HEALED ant_escalations:$ESC worklist_open:$WL → $REPORT ==="
