#!/usr/bin/env python3
import argparse
import contextlib
import copy
import json
import os
import re
import sys
from pathlib import Path

# Portable repo root: REPO_ROOT (per-invocation/worktree) -> METIS_HOME (canonical)
# -> self-locating fallback (<this file>/../..). Self-location is rename- and
# symlink-proof, so it survives removal of the Ant-openclaw-framework compat symlink.
ROOT = Path(os.environ.get("REPO_ROOT") or os.environ.get("METIS_HOME") or Path(__file__).resolve().parents[1])
TASKS_PATH = ROOT / "docs/process/state/tasks.json"
FOCUS_PATH = ROOT / "docs/process/state/live-focus.json"
AREAS_PATH = ROOT / "docs/process/state/task-areas.json"
PROJECTS_PATH = ROOT / "docs/process/state/projects.json"
TAXONOMY_PATH = ROOT / "docs/process/taxonomy.yaml"

# Board-projection enums (#100). area is validated against task-areas.json (one
# source of truth, shared with render-tier1-state.py); agent/machine are fixed.
VALID_AGENTS = {"smith", "scout", "warden", "scribe", "claude", "codex", "steward", "arbiter",
                # legacy lane names (pre-2026-06-13 Guild rename) — accepted so historical
                # tasks still transition; new work uses the names above.
                "forge", "shield", "echo", "hermes", "curator"}
def _valid_machines() -> set:
    """Valid machine ids. In a consuming org (the published metis-framework) the
    infra_config seam reads them from config/infrastructure.json, so ANY topology
    validates. In the canonical metis-os repo there is no such config -> fall back to
    the real roster. (#434: the seam must not reject a stranger's configured machine.)"""
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))
        import infra_config  # overlay-provided in metis-framework; absent in metis-os
        # valid_machine_tokens() = canonical ids + declared aliases/users + 'either',
        # so a not-yet-migrated pin (machine='<<MACHINE_2_ID>>') stays valid through the
        # <<MACHINE_2_ID>>->outpost rename window (Phase 1) instead of failing validation.
        toks = infra_config.valid_machine_tokens()
        if toks:
            return toks
    except Exception:
        pass
    return {"<<MACHINE_1_ID>>", "outpost", "<<MACHINE_2_ID>>", "either"}


VALID_MACHINES = _valid_machines()
BOARD_FIELDS = ("area", "agent", "machine")

VALID_TASK_STATES = {
    "inbox",
    "queued",
    "accepted",
    "in_progress",
    "execution_finished",
    "needs_verification",
    "waiting",
    "blocked",
    "failed",
    "done",
    "dropped",
}

ALLOWED_STATE_TRANSITIONS = {
    "inbox": {"queued", "accepted", "done", "dropped"},
    "queued": {"accepted", "waiting", "in_progress", "dropped"},
    "accepted": {"in_progress"},
    "in_progress": {"execution_finished", "waiting", "blocked", "failed"},
    "execution_finished": {"needs_verification"},
    "needs_verification": {"done", "blocked", "failed", "in_progress"},
    "waiting": {"in_progress"},
    "blocked": {"in_progress"},
    "failed": {"accepted", "in_progress"},
    "done": set(),
    "dropped": set(),
}

# States a never-worked suggestion can be dismissed FROM (#417). Dropping is for
# triage discard of untriaged/queued suggestions — NOT a way to retire real work
# in flight (use blocked/failed/correct-state for those). 'dropped' is terminal
# and honest: distinct from 'done' (completed) — no work happened, so no rich
# fields are required.
DISMISSABLE_STATES = {"inbox", "queued"}

TASK_MUTABLE_FIELDS = {
    "title",
    "displayTitle",  # optional: a concise, plain-language label for condensed UI (Watch Board, Plan cards, task lists). The canonical `title` stays logged/unchanged; UI falls back to `title` when absent. Generated by the local MLX lane (scripts/backfill-display-titles.py).
    "priority",
    "state",
    "owner",
    "summary",
    "why",
    "how",
    "currentStep",
    "firstStep",
    "expectedArtifact",
    "verificationMethod",
    "blockerOrNone",
    "nextAction",
    "mainFiles",
    "nextDecisionPoint",
    "stateCorrections",
    "planRef",  # optional: the planning/spec doc this task derives from (docs/plans/PLAN-*.md slug or a research/spec doc path) — makes the PLAN<->task link queryable, not freeform prose
    "idCollisionRenumberedFrom",  # set by merge-taskstate.py (#469) when a task-id collision renumbered this task to preserve it; the old id it carried

    "area",
    "agent",
    "machine",
    "project",
    "domain",
    "milestone",
    "origin",
    "originRef",
    "doneWhen",
    "decisionOptions",
    "recommendation",
    "decisionContext",
    "decision",  # resolved outcome: the chosen decisionOptions.key (writeback sets it)
    "createdAt",   # #285: set once at create (or backfilled); flow-instrumentation
    "completedAt",  # #285: set on the transition into done; flow-instrumentation
}

# queue-runner-v2 hybrid doneWhen contract (docs/process/queue-runner-v2-design.md).
# Optional today; the v2 runner executes/judges it so arbiter-approve == done
# honestly. type=check -> runnable command (exit 0 = pass); acceptance -> explicit
# criteria arbiter judges; both -> run the check AND confirm the criteria.
VALID_DONEWHEN_TYPES = {"check", "acceptance", "both"}

# WHO originated the task: ant=Ant directly asked; agent=agent proposed autonomously;
# collab=agent proposed, Ant approved; system=automated review/check caught it
VALID_ORIGINS = {"ant", "agent", "collab", "system"}


def _load_valid_domains():
    """Canonical domains from the SoT (docs/process/taxonomy.yaml); fail-open to the
    known set so a yaml hiccup never blocks a task write."""
    try:
        import pathlib
        import yaml
        spec = yaml.safe_load(
            (pathlib.Path(__file__).resolve().parents[1] / "docs/process/taxonomy.yaml").read_text())
        vals = set((spec.get("domains") or {}).keys())
        return vals or {"systems", "career", "finance", "health", "home", "craft", "presence", "joy"}
    except Exception:
        return {"systems", "career", "finance", "health", "home", "craft", "presence", "joy"}


VALID_DOMAINS = _load_valid_domains()

FOCUS_MUTABLE_FIELDS = {
    "focusSummary",
    "mode",
    "waitingOnAnt",
    "blockerSummary",
    "nextSteps",
    "derivedFromTaskIds",
}

CREATE_TASK_REQUIRED_FIELDS = {"taskId", "title", "priority", "state", "owner", "summary", "why", "how", "project"}
RICH_REQUIRED_STATES = {
    "accepted",
    "in_progress",
    "execution_finished",
    "needs_verification",
    "waiting",
    "blocked",
    "failed",
}
REQUIRED_RICH_FIELDS = [
    "currentStep",
    "expectedArtifact",
    "verificationMethod",
    "blockerOrNone",
    "nextAction",
]


def now_iso():
    from datetime import datetime

    return datetime.now().astimezone().isoformat(timespec="seconds")


CHECKOUTS_PATH = ROOT / "docs/process/state/active-checkouts.json"
# Lease statuses that are no longer live work — never re-stamp these (mirrors
# agent-work.py TERMINAL so a released/expired/stolen lease is not revived).
_LEASE_TERMINAL = {"done", "released", "blocked", "expired", "stolen", "abandoned"}


def restamp_lease_on_transition(task_id, old_state, new_state, checkouts_path=None):
    """#309 heartbeat-on-transition: when a task's state ACTUALLY changes, re-stamp
    the owning live lease's lastRenewedAt so stale-lease logic (reconcile I5 grace)
    never requeues actively-progressing work. Fires only on a real transition, and
    records liveness via lastRenewedAt ONLY — it never rewrites the lease's state
    backwards (the bug in the first smith attempt). Best-effort under an flock: a
    missing or locked checkouts file must never block the governed task write that
    already landed. Does not extend leaseExpiresAt — the lease's live/stale status
    for I1/I2 is unchanged; only the I5 crash-recovery grace consumes lastRenewedAt."""
    import re as _re
    from datetime import datetime, timezone
    if not old_state or old_state == new_state:
        return
    path = checkouts_path or CHECKOUTS_PATH
    m = _re.search(r"\d+", task_id or "")
    if not m or not path.exists():
        return
    num = m.group(0)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    lock_path = path.with_suffix(path.suffix + ".lock")
    try:
        import fcntl
        with lock_path.open("w") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            try:
                data = json.loads(path.read_text())
                mine = [r for r in data.get("checkouts", [])
                        if (str(r.get("issue")) == num or f"#{num}" in (r.get("title") or ""))
                        and r.get("status") not in _LEASE_TERMINAL]
                if mine:
                    holder = max(mine, key=lambda r: int(r.get("fenceToken", 0) or 0))
                    holder["lastRenewedAt"] = stamp
                    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
            finally:
                fcntl.flock(lock, fcntl.LOCK_UN)
    except Exception:
        return  # heartbeat is best-effort; the task state write is authoritative


def load_json(path: Path):
    return json.loads(path.read_text())


def dump_json(path: Path, data):
    # ensure_ascii=False preserves raw UTF-8 (en/em dashes, etc.) so governed
    # writes don't churn unrelated lines into \uXXXX escapes in the diff.
    #
    # Atomic write (#511): serialize to a temp file in the SAME directory, fsync,
    # then os.replace onto the target. os.replace is an atomic same-filesystem
    # rename, so a reader (or a mid-write kill) sees either the complete old file
    # or the complete new one — never a torn tasks.json. The same-dir tmp
    # guarantees the rename stays on one filesystem.
    import tempfile
    payload = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(payload)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


@contextlib.contextmanager
def tasks_lock(path: Path = None):
    """Exclusive inter-process lock over a mutator's load->validate->dump window (#511).

    The four mutators (create_task/update_task/correct_state/dismiss_task) each do
    load -> mutate -> dump. Revision-CAS only guards the SAME task, so two processes
    editing DIFFERENT tasks would both load the file, both mutate their own task, and
    the second dump would silently clobber the first. An flock on a '<file>.lock'
    sidecar serializes the whole window across processes (mirrors agent-work.py
    locked_state + restamp_lease_on_transition). Together with the atomic dump_json,
    concurrent mutations of different tasks both survive and no kill leaves a torn
    file. On a platform without fcntl the lock degrades to a no-op rather than
    crashing (single-writer assumption)."""
    path = path or TASKS_PATH
    lock_path = path.with_suffix(path.suffix + ".lock")
    try:
        import fcntl
    except ImportError:
        yield
        return
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock, fcntl.LOCK_UN)


# --- atomic governed-state commit (clobber-prevention) ------------------------
# A governed mutation written to tasks.json but left UNCOMMITTED can be silently
# lost. The auto-sync daemon (scripts/openclaw-git-sync.sh) has several paths that
# discard uncommitted working-tree changes: the bulk-deletion guard's `git reset`
# (when unrelated churn trips the delete limit), a pre-pull stash whose pop conflicts
# (`git reset --hard HEAD`), and stash pruning. The registered `taskstate` merge
# driver only protects COMMITTED blobs. So we commit the mutation the instant it is
# written, under the SAME mkdir lock the daemon uses — a committed change survives
# every daemon path (it's in HEAD / PRE_PULL_HEAD) and the merge driver unions it
# through any divergent pull. Best-effort: the canonical write already succeeded, so
# any git failure only falls back to (racy) daemon pickup and never fails the mutation.
_LOCK_DIR = Path(os.environ.get("OPENCLAW_LOCK_DIR") or (Path(os.environ.get("HOME", str(Path.home()))) / ".openclaw" / "locks"))  # override: isolate the lock for tests (#452)
_SYNC_LOCK = _LOCK_DIR / "git-sync.lock.d"
# Governed paths this CLI touches — a subset of the daemon's STATE_PATHSPECS: the
# canonical JSON plus the markdown projections render-tier1-state.py regenerates.
_COMMIT_PATHSPECS = [
    "docs/process/state/tasks.json",
    "docs/process/state/task-counter.json",
    "docs/process/state/live-focus.json",
    "docs/process/state/projects.json",
    "docs/process/taxonomy.yaml",
    "docs/process/task-queue.md",
    "docs/process/live-status.md",
    "docs/process/projects.md",
    "docs/process/task-naming-convention.md",
    "workspace/state/OPEN_TASKS.md",
]


def _holder_alive(pid_text):
    if not pid_text.isdigit():
        return False
    try:
        os.kill(int(pid_text), 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:  # exists, owned by another user — still alive
        return True
    except OSError:
        return False


def _holder_is_leaked(pid_text):
    """True iff the holder pid is a reclaimable leaked orphan — a bare `sleep`
    reparented to PID 1 after a SIGKILLed lock-holder (#452). Mirrors the bash
    holder_is_leaked() in scripts/lib/git-sync-lock.sh. Conservative: returns False
    unless certain, so a legitimate live holder is never stolen. (macOS launchd is
    PID 1, so the bare-`sleep` command match — not PPID alone — is the safe signal.)"""
    import subprocess
    if not pid_text.isdigit():
        return False
    try:
        out = subprocess.run(
            ["ps", "-o", "ppid=,comm=", "-p", pid_text],
            capture_output=True, text=True,
        ).stdout.strip()
    except OSError:
        return False
    if not out:
        return False  # no such process (dead) — handled by the dead-pid path
    parts = out.split(None, 1)
    if len(parts) != 2:
        return False
    ppid, cmd = parts[0], parts[1].strip()
    if ppid != "1":
        return False  # has a live parent → genuine holder
    base = cmd.rsplit("/", 1)[-1]
    return base == "sleep"


def _acquire_sync_lock(timeout=30):
    """Acquire the daemon's mkdir lock (with stale-holder reclaim). Returns True on
    success, False if it couldn't be taken within `timeout`s — the caller then skips
    the commit and relies on daemon pickup, so task creation never hangs on a wedged
    lock. Mirrors scripts/git-lock.sh / openclaw-git-sync.sh acquire semantics."""
    import time
    import shutil
    _LOCK_DIR.mkdir(parents=True, exist_ok=True)
    deadline = time.monotonic() + timeout
    while True:
        try:
            _SYNC_LOCK.mkdir()
            (_SYNC_LOCK / "pid").write_text(str(os.getpid()))
            return True
        except FileExistsError:
            try:
                holder = (_SYNC_LOCK / "pid").read_text().strip()
            except OSError:
                holder = ""
            if _holder_alive(holder) and not _holder_is_leaked(holder):
                if time.monotonic() >= deadline:
                    return False
                time.sleep(1)
                continue
            # dead, unknown, OR a leaked orphan holder (#452) — reclaim and retry
            shutil.rmtree(_SYNC_LOCK, ignore_errors=True)


def _release_sync_lock():
    import shutil
    shutil.rmtree(_SYNC_LOCK, ignore_errors=True)


def _git(*args):
    import subprocess
    return subprocess.run(["git", *args], cwd=str(ROOT), capture_output=True, text=True)


def _heal_stale_index_lock():
    """Remove .git/index.lock IFF no live process owns it (mirrors git-lock.sh). A
    crashed git leaves this behind and blocks every later git op; a live holder is
    left alone (we retry instead). Returns True if a stale lock was cleared."""
    import subprocess
    r = _git("rev-parse", "--git-dir")
    if r.returncode != 0:
        return False
    lock = (ROOT / r.stdout.strip() / "index.lock") if not os.path.isabs(r.stdout.strip()) \
        else Path(r.stdout.strip()) / "index.lock"
    if not lock.exists():
        return False
    owner = subprocess.run(["lsof", str(lock)], capture_output=True, text=True)
    # lsof prints a header + a row per owning process; no rows => no live owner.
    if owner.returncode == 0 and len(owner.stdout.strip().splitlines()) > 1:
        return False  # a live process owns it — don't steal
    try:
        lock.unlink()
        return True
    except OSError:
        return False


def _git_locked(*args, retries=6):
    """Run a mutating git op, resilient to a concurrent process holding .git/index.lock.
    A different session/hook (which doesn't take our sync lock) can hold index.lock; we
    heal it if stale, else wait and retry. Returns the final CompletedProcess."""
    import time
    r = _git(*args)
    attempt = 0
    while r.returncode != 0 and "index.lock" in (r.stderr or "") and attempt < retries:
        if not _heal_stale_index_lock():
            time.sleep(0.5)  # live holder — let it finish, then retry
        attempt += 1
        r = _git(*args)
    return r


def commit_governed_state(label):
    """Render projections, then commit the governed-state pathspecs under the daemon's
    sync lock so the mutation is durable the instant it is written. Commit-only (no
    push): a local commit on `main` is already clobber-proof — the daemon pushes it on
    its next tick and the `taskstate` merge driver reconciles any divergence. Never
    raises; returns True iff a commit was actually made."""
    import subprocess
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return False  # never commit the real repo from inside a test run (tests monkeypatch TASKS_PATH to a tmp file; the commit would otherwise sweep unrelated staged changes into a mislabeled task() commit)
    if not (ROOT / ".git").exists():
        return False  # not a real checkout (e.g. a sandbox) — nothing to commit
    if not _acquire_sync_lock():
        print("NOTE: sync lock busy — commit deferred to auto-sync daemon (change IS written)",
              file=sys.stderr)
        return False
    try:
        render = Path(__file__).resolve().parent / "render-tier1-state.py"
        if render.exists():
            r = subprocess.run([sys.executable, str(render), "write"], cwd=str(ROOT),
                               capture_output=True, text=True)
            if r.returncode != 0:
                print(f"WARN: projection render failed: {(r.stderr or '').strip()[:300]}",
                      file=sys.stderr)
        present = [p for p in _COMMIT_PATHSPECS if (ROOT / p).exists()]
        if not present:
            return False
        add = _git_locked("add", "--", *present)
        if add.returncode != 0:
            print(f"WARN: git add failed: {add.stderr.strip()[:300]}; daemon will pick up",
                  file=sys.stderr)
            return False
        if _git("diff", "--cached", "--quiet", "--", *present).returncode == 0:
            return False  # nothing staged (identical content) — clean no-op
        commit = _git_locked("commit", "-m", label, "--", *present)
        if commit.returncode != 0:
            print(f"WARN: git commit failed: {commit.stderr.strip()[:300]}; daemon will pick up",
                  file=sys.stderr)
            return False
        print(f"committed governed state: {label}")
        return True
    finally:
        _release_sync_lock()


def parse_patch(patch_text: str):
    try:
        patch = json.loads(patch_text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid patch JSON: {exc}")
    if not isinstance(patch, dict):
        raise ValueError("patch must decode to a JSON object")
    return patch


def validate_task_shape(task_id: str, task: dict, require_rich: bool = True):
    state = task.get("state")
    if state not in VALID_TASK_STATES:
        raise ValueError(f"{task_id}: invalid state {state!r}")

    if require_rich and state in RICH_REQUIRED_STATES:
        missing = [field for field in REQUIRED_RICH_FIELDS if not task.get(field)]
        if missing:
            raise ValueError(
                f"{task_id}: missing required rich fields for state {state}: {', '.join(missing)}"
            )

    if state == "done" and task.get("blockerOrNone") not in (None, "", "none"):
        raise ValueError(f"{task_id}: done task should not carry a meaningful blocker")

    if state == "execution_finished" and not task.get("verificationMethod"):
        raise ValueError(f"{task_id}: execution_finished task must preserve verificationMethod")

    validate_done_when(task_id, task)
    validate_decision(task_id, task)


def validate_title(task_id: str, task: dict):
    """Titles must STAND ALONE (Ant 2026-06-29): a "#NNN" task-number reference in a
    title is meaningless without looking that number up, and makes tasks hard to tell
    apart on the board and in conversation. Reject a task-number token in the title so
    every title is self-descriptive and distinguishable. Applied at create time only
    (legacy titles are grandfathered)."""
    title = str(task.get("title", ""))
    numref = re.search(r"#\d{2,}", title)
    if numref:
        raise ValueError(
            f"{task_id}: title must stand alone — a '{numref.group()}' task-number "
            f"reference is meaningless without lookup. Rewrite it descriptively: {title!r}"
        )


def validate_decision(task_id: str, task: dict):
    """Validate the optional structured decision affordances (#323, decision-inbox).
    Both Notion and Control Center render these instead of scraping nextDecisionPoint prose:
      decisionOptions: [{"key": "a", "label": "...", "detail"?: "..."}]  # the one-tap choices
      recommendation:  "<key or short text> — why"                       # agent's pick
      decisionContext: "why it matters / trade-offs / links"             # context to decide
    """
    opts = task.get("decisionOptions")
    if opts is not None:
        if not isinstance(opts, list) or not opts:
            raise ValueError(f"{task_id}: decisionOptions must be a non-empty list")
        keys = set()
        for o in opts:
            if not isinstance(o, dict):
                raise ValueError(f"{task_id}: each decisionOption must be an object {{key,label}}")
            k, label = o.get("key"), o.get("label")
            if not isinstance(k, str) or not k.strip():
                raise ValueError(f"{task_id}: decisionOption needs a non-empty 'key'")
            if not isinstance(label, str) or not label.strip():
                raise ValueError(f"{task_id}: decisionOption {k!r} needs a non-empty 'label'")
            if "detail" in o and not isinstance(o["detail"], str):
                raise ValueError(f"{task_id}: decisionOption {k!r} 'detail' must be a string")
            if k in keys:
                raise ValueError(f"{task_id}: duplicate decisionOption key {k!r}")
            keys.add(k)
    for f in ("recommendation", "decisionContext"):
        v = task.get(f)
        if v is not None and (not isinstance(v, str) or not v.strip()):
            raise ValueError(f"{task_id}: {f} must be a non-empty string when present")


def validate_done_when(task_id: str, task: dict):
    """Validate the optional structured doneWhen (queue-runner-v2). When present it
    must be USABLE — the v2 runner executes the check or arbiter judges the
    criteria, so a malformed contract would silently break the apply+verify loop.
      {"type": "check"|"acceptance"|"both",
       "check": "<shell command, exit 0 = pass>",   # required for check/both
       "criteria": ["explicit acceptance bullet", ...]}  # required for acceptance/both
    """
    dw = task.get("doneWhen")
    if dw is None:
        return
    if not isinstance(dw, dict):
        raise ValueError(f"{task_id}: doneWhen must be an object")
    dtype = dw.get("type")
    if dtype not in VALID_DONEWHEN_TYPES:
        raise ValueError(
            f"{task_id}: doneWhen.type must be one of {', '.join(sorted(VALID_DONEWHEN_TYPES))}"
        )
    if dtype in {"check", "both"}:
        check = dw.get("check")
        if not isinstance(check, str) or not check.strip():
            raise ValueError(
                f"{task_id}: doneWhen.type={dtype} requires a non-empty 'check' command string"
            )
    if dtype in {"acceptance", "both"}:
        crit = dw.get("criteria")
        if not isinstance(crit, list) or not crit or not all(
            isinstance(c, str) and c.strip() for c in crit
        ):
            raise ValueError(
                f"{task_id}: doneWhen.type={dtype} requires a non-empty 'criteria' list of strings"
            )


def load_valid_areas():
    """Area names from task-areas.json — single source of truth shared with the
    projector. Returns an empty set if the file is missing/unreadable so the enum
    check degrades to a no-op rather than blocking writes on a config error."""
    try:
        doc = json.loads(AREAS_PATH.read_text())
        return {a["name"] for a in doc.get("areas", [])}
    except (OSError, ValueError):
        return set()


def load_valid_project_slugs():
    """Project slugs from projects.json. Returns empty set on missing/unreadable file."""
    try:
        doc = json.loads(PROJECTS_PATH.read_text())
        return {p["slug"] for p in doc.get("projects", [])}
    except (OSError, ValueError):
        return set()


def validate_board_fields(task_id: str, task: dict, require_present: bool = True):
    """Gate the board-projection fields (#100). Presence is required only for
    born-governed tasks (require_present=True); enum-validity is always enforced
    when a value is given. Mirrors the require_rich/--backfill split above.

    #517: collects EVERY violation and raises once — the old first-fail raise made
    callers discover requirements one error at a time (a #909-era create took four
    round-trips: create-required, unknown-field, board-presence, then origin)."""
    errors = []
    if require_present:
        missing = [f for f in BOARD_FIELDS if not task.get(f)]
        if missing:
            errors.append(f"missing required board fields: {', '.join(missing)}")

    area = task.get("area")
    if area is not None:
        valid_areas = load_valid_areas()
        if valid_areas and area not in valid_areas:
            errors.append(
                f"invalid area {area!r} (not in task-areas.json: {', '.join(sorted(valid_areas))})"
            )

    project = task.get("project")
    valid_projects = load_valid_project_slugs()
    if valid_projects:
        if project is None or project == "":
            errors.append(
                f"missing required project field (valid slugs: {', '.join(sorted(valid_projects))})"
            )
        elif project not in valid_projects:
            errors.append(
                f"invalid project slug {project!r} (not in projects.json: {', '.join(sorted(valid_projects))})"
            )

    agent = task.get("agent")
    if agent is not None and agent not in VALID_AGENTS:
        errors.append(f"invalid agent {agent!r} (valid: {', '.join(sorted(VALID_AGENTS))})")
    machine = task.get("machine")
    if machine is not None and machine not in VALID_MACHINES:
        errors.append(f"invalid machine {machine!r} (valid: {', '.join(sorted(VALID_MACHINES))})")

    origin = task.get("origin")
    if require_present and origin is None:
        errors.append(f"missing required field: origin (valid: {', '.join(sorted(VALID_ORIGINS))})")
    if origin is not None and origin not in VALID_ORIGINS:
        errors.append(f"invalid origin {origin!r} (valid: {', '.join(sorted(VALID_ORIGINS))})")

    domain = task.get("domain")
    if domain is not None and domain not in VALID_DOMAINS:
        errors.append(f"invalid domain {domain!r} (valid: {', '.join(sorted(VALID_DOMAINS))})")

    if errors:
        raise ValueError(f"{task_id}: " + "; ".join(errors))


def validate_task_patch(task_id: str, patch: dict):
    unknown = sorted(set(patch.keys()) - TASK_MUTABLE_FIELDS)
    if unknown:
        raise ValueError(f"{task_id}: unknown task patch fields: {', '.join(unknown)}")
    state = patch.get("state")
    if state is not None and state not in VALID_TASK_STATES:
        raise ValueError(f"{task_id}: invalid state {state!r}")


def validate_focus_patch(patch: dict):
    unknown = sorted(set(patch.keys()) - FOCUS_MUTABLE_FIELDS)
    if unknown:
        raise ValueError(f"live-focus: unknown patch fields: {', '.join(unknown)}")


def validate_state_transition(task_id: str, old_state: str, new_state: str):
    if old_state == new_state:
        return
    allowed = ALLOWED_STATE_TRANSITIONS.get(old_state, set())
    if new_state not in allowed:
        raise ValueError(f"{task_id}: invalid state transition {old_state!r} -> {new_state!r}")


def validate_done_gate(task_id: str, old_state: str, task: dict):
    if task.get("state") != "done":
        return
    if old_state == "done":
        # No transition is occurring — the task is already done and the patch
        # touches non-state fields (e.g. a project refile). The gate guards the
        # *move* into done; re-tripping it here made every done task immutable.
        return
    if old_state != "needs_verification":
        raise ValueError(f"{task_id}: done is only allowed from needs_verification")
    if task.get("blockerOrNone") not in (None, "", "none"):
        raise ValueError(f"{task_id}: done requires blockerOrNone to be none")
    next_action = task.get("nextAction")
    if next_action not in (None, "", "none"):
        raise ValueError(f"{task_id}: done requires nextAction to be none or empty")
    if not task.get("expectedArtifact"):
        raise ValueError(f"{task_id}: done requires expectedArtifact")
    if not task.get("verificationMethod"):
        raise ValueError(f"{task_id}: done requires verificationMethod")


def create_task(args):
    doc = load_json(TASKS_PATH)
    tasks = doc.get("tasks", [])
    new_task = parse_patch(args.patch)

    # #517: run EVERY validation gate and report all failures in one message —
    # the old first-fail flow made a caller discover create requirements across
    # four sequential error round-trips (create-required -> unknown-field ->
    # board-presence -> origin, seen live minting the 2026-07-08 incident task).
    errors = []

    missing = sorted(CREATE_TASK_REQUIRED_FIELDS - set(new_task.keys()))
    if missing:
        errors.append(f"missing required fields: {', '.join(missing)}")

    try:
        validate_title("create-task", new_task)
    except ValueError as exc:
        errors.append(str(exc))

    # Canonical taskId form is "#NNN" (see docs/process/task-naming-convention.md).
    # alloc-id prints the bare number, so a caller that forwards it verbatim would
    # store a prefix-less id that collides on number with a real "#NNN" task and
    # misses every "#NNN" exact-match lookup (e.g. the born-governed guard). Coerce
    # a bare-numeric id to "#NNN" here, and reject anything that isn't "#"+digits.
    raw_id = str(new_task.get("taskId", "")).strip()
    if raw_id.isdigit():
        raw_id = "#" + raw_id
    if not re.fullmatch(r"#\d+", raw_id):
        errors.append(
            f"taskId must be '#NNN' (got {new_task.get('taskId')!r}); "
            f"use the alloc-id number prefixed with '#'"
        )
        raw_id = None
    if raw_id:
        new_task["taskId"] = raw_id
        if any(t.get("taskId") == raw_id for t in tasks):
            errors.append(f"task already exists: {raw_id}")
    task_id = raw_id or "create-task"

    unknown = sorted(set(new_task.keys()) - (TASK_MUTABLE_FIELDS | {"taskId"}))
    if unknown:
        errors.append(f"unknown task fields: {', '.join(unknown)}")

    task = copy.deepcopy(new_task)
    task.setdefault("mainFiles", [])
    task.setdefault("nextDecisionPoint", None)
    task["updatedAt"] = now_iso()
    task["updatedBy"] = args.actor
    task["revision"] = 1
    # #285: createdAt is set once, at birth. A --backfill import (or an explicit
    # patch carrying createdAt) preserves the historical value; a fresh create
    # stamps it equal to updatedAt. It is never bumped again (see update_task).
    task["createdAt"] = task.get("createdAt") or task["updatedAt"]

    backfill = getattr(args, "backfill", False)
    for gate in (
        lambda: validate_task_shape(task_id, task, require_rich=not backfill),
        lambda: validate_board_fields(task_id, task, require_present=not backfill),
        lambda: (None if backfill else validate_done_gate(task_id, None, task)),
    ):
        try:
            gate()
        except ValueError as exc:
            errors.append(str(exc))

    if errors:
        raise ValueError(
            "create-task: "
            + "\n  - ".join([""] + errors)
            + "\n  (full field reference: update-tier1-state.py schema)"
        )

    if args.check:
        print(json.dumps(task, indent=2))
        return

    tasks.append(task)
    doc["updatedAt"] = task["updatedAt"]
    dump_json(TASKS_PATH, doc)
    print(f"Created task {task_id} -> revision {task['revision']}")
    _catchup_task_counter(task_id)

    # #447: commit the new task immediately so a daemon sync can't clobber it in the
    # uncommitted window (the root cause of vanished tasks). Default-on for a normal
    # create; skipped for --backfill (bulk migration imports commit once at the end)
    # and when --no-commit is passed (caller batches its own commit).
    if not backfill and not getattr(args, "no_commit", False):
        title = (task.get("title") or task.get("summary") or "").strip()
        commit_governed_state(f"task({task_id}): create" + (f" — {title[:60]}" if title else ""))


# ── Project / milestone creation (governed writes to projects.json + taxonomy) ──
# tasks.json carries a `project` slug + optional `milestone` id, but the project
# and milestone RECORDS live in projects.json (with milestones nested per project)
# and the project→domain link lives in taxonomy.yaml `project_domain:`. These two
# mutators mint those records so the Plan drill-down can grow the tree, the
# same auto-commit-under-lock discipline as create-task.

def _slugify(name):
    s = re.sub(r"[^a-z0-9]+", "-", str(name or "").strip().lower()).strip("-")
    return s or "project"


def _mint_next_id(existing_ids, prefix, pad=0):
    """Next monotonic `<prefix><n>` id (e.g. P20, M4) above the max existing one."""
    nums = []
    for i in existing_ids:
        m = re.fullmatch(re.escape(prefix) + r"(\d+)", str(i or ""))
        if m:
            nums.append(int(m.group(1)))
    n = (max(nums) + 1) if nums else 1
    return f"{prefix}{n:0{pad}d}" if pad else f"{prefix}{n}"


def _set_taxonomy_project_domain(slug, domain):
    """Surgically add `  <slug>: <domain>` under the `project_domain:` block in
    taxonomy.yaml, preserving every comment/line (yaml.safe_dump would strip the
    file's heavy commentary). Idempotent — rewrites the line if the slug already
    maps. The backend re-reads taxonomy.yaml per request, so no restart is needed."""
    lines = TAXONOMY_PATH.read_text().splitlines(keepends=True)
    start = next((i for i, ln in enumerate(lines) if re.match(r"^project_domain:\s*$", ln)), None)
    if start is None:
        raise ValueError("taxonomy.yaml: no project_domain: block to extend")
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if re.match(r"^[A-Za-z0-9_]+:", lines[j]):  # next top-level key ends the block
            end = j
            break
    entry_re = re.compile(r"^\s+" + re.escape(slug) + r":\s*\S")
    for j in range(start + 1, end):
        if entry_re.match(lines[j]):
            lines[j] = f"  {slug}: {domain}\n"
            TAXONOMY_PATH.write_text("".join(lines))
            return
    insert_at = end
    while insert_at - 1 > start and lines[insert_at - 1].strip() == "":
        insert_at -= 1  # keep the mapping inside the block, above trailing blanks
    lines.insert(insert_at, f"  {slug}: {domain}\n")
    TAXONOMY_PATH.write_text("".join(lines))


def create_project(args):
    patch = parse_patch(args.patch)
    name = str(patch.get("name") or "").strip()
    if not name:
        raise ValueError("create-project: 'name' is required")
    priority = str(patch.get("priority") or "P2").strip()
    if priority not in {"P1", "P2", "P3"}:
        raise ValueError(f"create-project: invalid priority {priority!r} (P1/P2/P3)")
    domain = str(patch.get("domain") or "").strip()
    if domain not in VALID_DOMAINS:
        raise ValueError(f"create-project: invalid domain {domain!r} (valid: {', '.join(sorted(VALID_DOMAINS))})")
    goal = str(patch.get("goal") or "").strip() or None
    if goal and (valid_goals := _valid_goals()) and goal not in valid_goals:
        raise ValueError(f"create-project: invalid goal {goal!r} (valid: {', '.join(sorted(valid_goals))})")

    doc = load_json(PROJECTS_PATH)
    projects = doc.get("projects", [])
    project_id = _mint_next_id([p.get("projectId") for p in projects], "P", pad=2)
    base_slug = _slugify(patch.get("slug") or name)
    existing_slugs = {p.get("slug") for p in projects}
    slug, n = base_slug, 2
    while slug in existing_slugs:
        slug, n = f"{base_slug}-{n}", n + 1

    # Optional seeded milestones (draft-then-apply auto build-out): a list of
    # {title, doneWhen} minted into M1..Mn so a new project can arrive with a
    # skeleton ladder in one atomic write. Empty-titled entries are dropped.
    seeded = []
    for i, m in enumerate(patch.get("milestones") or [], start=1):
        mt = str((m or {}).get("title") or "").strip()
        if not mt:
            continue
        seeded.append({
            "id": f"M{len(seeded) + 1}",
            "title": mt,
            "doneWhen": str((m or {}).get("doneWhen") or "").strip() or None,
            "status": "todo",
            "weight": 1,
            "fill": 0.0,
            "taskIds": [],
            "completedAt": None,
        })

    record = {
        "projectId": project_id,
        "slug": slug,
        "name": name,
        "goal": goal,
        "status": "active",
        "priority": priority,
        "doneWhen": str(patch.get("doneWhen") or "").strip() or None,
        "scope": str(patch.get("scope") or "").strip() or None,
        "updatedAt": now_iso(),
        "milestones": seeded,
    }
    if args.check:
        print(json.dumps({"project": record, "taxonomy_project_domain": {slug: domain}}, indent=2))
        return

    projects.append(record)
    doc["updatedAt"] = record["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    _set_taxonomy_project_domain(slug, domain)
    print(f"Created project {project_id} ({slug}) in domain {domain}"
          + (f" with {len(seeded)} seeded milestone(s)" if seeded else ""))
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"project({slug}): create — {name[:60]}")


def create_milestone(args):
    patch = parse_patch(args.patch)
    slug = str(patch.get("projectSlug") or patch.get("project") or "").strip()
    title = str(patch.get("title") or "").strip()
    if not slug or not title:
        raise ValueError("create-milestone: 'projectSlug' and 'title' are required")

    doc = load_json(PROJECTS_PATH)
    projects = doc.get("projects", [])
    proj = next((p for p in projects if p.get("slug") == slug), None)
    if proj is None:
        raise ValueError(f"create-milestone: no project with slug {slug!r}")
    milestones = proj.setdefault("milestones", [])
    mid = _mint_next_id([m.get("id") for m in milestones], "M")

    record = {
        "id": mid,
        "title": title,
        "doneWhen": str(patch.get("doneWhen") or "").strip() or None,
        "status": "active",
        "weight": int(patch.get("weight") or 1),
        "fill": 0.0,
        "taskIds": [],
        "completedAt": None,
    }
    if args.check:
        print(json.dumps({"project": slug, "milestone": record}, indent=2))
        return

    milestones.append(record)
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    print(f"Created milestone {mid} in project {slug}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"milestone({slug}/{mid}): create — {title[:60]}")


def _remove_taxonomy_project_domain(slug):
    """Remove the `  <slug>: <domain>` line from taxonomy.yaml's project_domain
    block, preserving every other line/comment. Idempotent (no-op if absent)."""
    lines = TAXONOMY_PATH.read_text().splitlines(keepends=True)
    start = next((i for i, ln in enumerate(lines) if re.match(r"^project_domain:\s*$", ln)), None)
    if start is None:
        return
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if re.match(r"^[A-Za-z0-9_]+:", lines[j]):
            end = j
            break
    entry_re = re.compile(r"^\s+" + re.escape(slug) + r":\s*\S")
    for j in range(start + 1, end):
        if entry_re.match(lines[j]):
            del lines[j]
            TAXONOMY_PATH.write_text("".join(lines))
            return


# projects.json status is a free string; these are the values the UI edit/archive
# paths may set (existing data uses active/paused/blocked/todo/done — we add archived).
VALID_PROJECT_STATUS = {"active", "paused", "blocked", "archived", "done"}
VALID_MILESTONE_STATUS = {"todo", "active", "blocked", "done", "archived"}
_PROJECT_EDITABLE = {"name", "priority", "doneWhen", "scope", "goal", "status", "evergreen"}
_MILESTONE_EDITABLE = {"title", "doneWhen", "weight", "status"}


def _valid_goals():
    """The campaign/goal ids (G1..G6) defined in taxonomy.yaml, or empty if it can't
    be read (in which case goal validation is skipped rather than blocking a create)."""
    try:
        import yaml
        tx = yaml.safe_load(TAXONOMY_PATH.read_text()) or {}
        return set((tx.get("campaigns") or {}).keys())
    except Exception:
        return set()


def _find_project(doc, slug):
    proj = next((p for p in doc.get("projects", []) if p.get("slug") == slug), None)
    if proj is None:
        raise ValueError(f"no project with slug {slug!r}")
    return proj


def update_project(args):
    """Patch editable fields on a project record (name/priority/doneWhen/scope/goal/
    status, plus domain via the taxonomy link). tasks_lock serializes writes — projects
    carry no per-record revision, so the lock is the concurrency guard (like create)."""
    patch = parse_patch(args.patch)
    slug = str(getattr(args, "slug", "") or "").strip()
    if not slug:
        raise ValueError("update-project: --slug is required")
    doc = load_json(PROJECTS_PATH)
    proj = _find_project(doc, slug)

    unknown = set(patch) - _PROJECT_EDITABLE - {"domain"}
    if unknown:
        raise ValueError(f"update-project: non-editable field(s): {', '.join(sorted(unknown))}")
    if "name" in patch and not str(patch["name"]).strip():
        raise ValueError("update-project: 'name' cannot be blank")
    if "priority" in patch and str(patch["priority"]) not in {"P1", "P2", "P3"}:
        raise ValueError(f"update-project: invalid priority {patch['priority']!r} (P1/P2/P3)")
    if "status" in patch and str(patch["status"]) not in VALID_PROJECT_STATUS:
        raise ValueError(
            f"update-project: invalid status {patch['status']!r} (valid: {', '.join(sorted(VALID_PROJECT_STATUS))})"
        )
    if "evergreen" in patch and not isinstance(patch["evergreen"], bool):
        raise ValueError(f"update-project: 'evergreen' must be true/false, got {patch['evergreen']!r}")
    new_domain = None
    if "domain" in patch:
        new_domain = str(patch["domain"]).strip()
        if new_domain not in VALID_DOMAINS:
            raise ValueError(f"update-project: invalid domain {new_domain!r} (valid: {', '.join(sorted(VALID_DOMAINS))})")

    updated = copy.deepcopy(proj)
    for k in _PROJECT_EDITABLE:
        if k in patch:
            v = patch[k]
            if k == "name":
                v = str(v).strip()
            elif k in {"doneWhen", "scope", "goal"}:
                v = str(v).strip() or None
            updated[k] = v
    updated["updatedAt"] = now_iso()

    if args.check:
        print(json.dumps({"project": updated, "domain": new_domain}, indent=2))
        return

    proj.clear()
    proj.update(updated)
    doc["updatedAt"] = updated["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    if new_domain:
        _set_taxonomy_project_domain(slug, new_domain)
    print(f"Updated project {slug}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"project({slug}): update")


def archive_project(args):
    """Soft-remove: status -> archived. Reversible (update-project status=active),
    keeps the record + any linked tasks/milestones intact. The safe default over delete."""
    slug = str(getattr(args, "slug", "") or "").strip()
    if not slug:
        raise ValueError("archive-project: --slug is required")
    doc = load_json(PROJECTS_PATH)
    proj = _find_project(doc, slug)
    if args.check:
        print(json.dumps({"archive_project": slug, "status": "archived"}, indent=2))
        return
    proj["status"] = "archived"
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    print(f"Archived project {slug}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"project({slug}): archive")


def delete_project(args):
    """Hard-delete a project record + its taxonomy link — but ONLY when empty (no
    milestones and no tasks reference it), so nothing is orphaned. For a fat-finger
    mistaken create. Anything with content must be archived instead."""
    slug = str(getattr(args, "slug", "") or "").strip()
    if not slug:
        raise ValueError("delete-project: --slug is required")
    doc = load_json(PROJECTS_PATH)
    proj = _find_project(doc, slug)
    milestones = proj.get("milestones") or []
    if milestones:
        raise ValueError(
            f"delete-project: {slug} has {len(milestones)} milestone(s) — archive it, or delete the milestones first"
        )
    tdoc = load_json(TASKS_PATH)
    # 'dropped' tasks are explicitly discarded — they don't pin the project alive.
    refs = [t.get("taskId") for t in tdoc.get("tasks", []) if t.get("project") == slug and t.get("state") != "dropped"]
    if refs:
        raise ValueError(
            f"delete-project: {slug} is referenced by {len(refs)} live task(s) (e.g. {refs[0]}) — archive it instead"
        )
    if args.check:
        print(json.dumps({"delete_project": slug, "empty": True}, indent=2))
        return
    doc["projects"] = [p for p in doc.get("projects", []) if p.get("slug") != slug]
    doc["updatedAt"] = now_iso()
    dump_json(PROJECTS_PATH, doc)
    _remove_taxonomy_project_domain(slug)
    print(f"Deleted project {slug}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"project({slug}): delete (empty)")


def _find_milestone(doc, slug, mid):
    proj = _find_project(doc, slug)
    ms = next((m for m in proj.get("milestones", []) if m.get("id") == mid), None)
    if ms is None:
        raise ValueError(f"no milestone {mid} in project {slug!r}")
    return proj, ms


def update_milestone(args):
    patch = parse_patch(args.patch)
    slug = str(getattr(args, "slug", "") or "").strip()
    mid = str(getattr(args, "milestone_id", "") or "").strip()
    if not slug or not mid:
        raise ValueError("update-milestone: --slug and --milestone-id are required")
    doc = load_json(PROJECTS_PATH)
    proj, ms = _find_milestone(doc, slug, mid)

    unknown = set(patch) - _MILESTONE_EDITABLE
    if unknown:
        raise ValueError(f"update-milestone: non-editable field(s): {', '.join(sorted(unknown))}")
    if "title" in patch and not str(patch["title"]).strip():
        raise ValueError("update-milestone: 'title' cannot be blank")
    if "status" in patch and str(patch["status"]) not in VALID_MILESTONE_STATUS:
        raise ValueError(
            f"update-milestone: invalid status {patch['status']!r} (valid: {', '.join(sorted(VALID_MILESTONE_STATUS))})"
        )

    updated = copy.deepcopy(ms)
    for k in _MILESTONE_EDITABLE:
        if k in patch:
            v = patch[k]
            if k == "title":
                v = str(v).strip()
            elif k == "doneWhen":
                v = str(v).strip() or None
            elif k == "weight":
                v = int(v)
            updated[k] = v

    if args.check:
        print(json.dumps({"project": slug, "milestone": updated}, indent=2))
        return

    ms.clear()
    ms.update(updated)
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    print(f"Updated milestone {slug}/{mid}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"milestone({slug}/{mid}): update")


def archive_milestone(args):
    slug = str(getattr(args, "slug", "") or "").strip()
    mid = str(getattr(args, "milestone_id", "") or "").strip()
    if not slug or not mid:
        raise ValueError("archive-milestone: --slug and --milestone-id are required")
    doc = load_json(PROJECTS_PATH)
    proj, ms = _find_milestone(doc, slug, mid)
    if args.check:
        print(json.dumps({"archive_milestone": f"{slug}/{mid}", "status": "archived"}, indent=2))
        return
    ms["status"] = "archived"
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    print(f"Archived milestone {slug}/{mid}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"milestone({slug}/{mid}): archive")


def delete_milestone(args):
    """Hard-delete a milestone — ONLY when it holds no tasks (taskIds empty and no
    task's milestone points at it), so no task is orphaned. Else archive it."""
    slug = str(getattr(args, "slug", "") or "").strip()
    mid = str(getattr(args, "milestone_id", "") or "").strip()
    if not slug or not mid:
        raise ValueError("delete-milestone: --slug and --milestone-id are required")
    doc = load_json(PROJECTS_PATH)
    proj, ms = _find_milestone(doc, slug, mid)
    tdoc = load_json(TASKS_PATH)
    dropped = {t.get("taskId") for t in tdoc.get("tasks", []) if t.get("state") == "dropped"}
    task_ids = [tid for tid in (ms.get("taskIds") or []) if tid not in dropped]  # dropped tasks don't pin the milestone
    refs = [t.get("taskId") for t in tdoc.get("tasks", []) if t.get("milestone") == mid and t.get("project") == slug and t.get("state") != "dropped"]
    if task_ids or refs:
        n = len(set(task_ids) | set(refs))
        raise ValueError(f"delete-milestone: {slug}/{mid} holds {n} live task(s) — archive it, or move the tasks first")
    if args.check:
        print(json.dumps({"delete_milestone": f"{slug}/{mid}", "empty": True}, indent=2))
        return
    proj["milestones"] = [m for m in proj.get("milestones", []) if m.get("id") != mid]
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)
    print(f"Deleted milestone {slug}/{mid}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"milestone({slug}/{mid}): delete (empty)")


def reassign_task(args):
    """Move a task between milestones within its project, or unassign it. Milestone
    membership for the Plan drill is authoritative in each milestone's taskIds[]
    (the projection ignores task.milestone), so this edits taskIds; it also keeps
    the secondary task.milestone field in sync. --unassign removes it from all."""
    task_id = args.task_id.strip()
    slug = args.project.strip()
    target = None if args.unassign else str(args.to_milestone or "").strip()
    if not args.unassign and not target:
        raise ValueError("reassign-task: pass --to-milestone <M#> or --unassign")

    doc = load_json(PROJECTS_PATH)
    proj = _find_project(doc, slug)
    milestones = proj.get("milestones") or []
    if target and not any(m.get("id") == target for m in milestones):
        raise ValueError(f"reassign-task: no milestone {target} in project {slug!r}")

    if args.check:
        print(json.dumps({"reassign": task_id, "project": slug, "to": target or "unassigned"}, indent=2))
        return

    for m in milestones:
        tids = m.get("taskIds") or []
        if task_id in tids:
            m["taskIds"] = [x for x in tids if x != task_id]
    if target:
        tgt = next(m for m in milestones if m.get("id") == target)
        tgt.setdefault("taskIds", [])
        if task_id not in tgt["taskIds"]:
            tgt["taskIds"].append(task_id)
    proj["updatedAt"] = now_iso()
    doc["updatedAt"] = proj["updatedAt"]
    dump_json(PROJECTS_PATH, doc)

    # Keep the secondary task.milestone field consistent (few readers use it).
    tdoc = load_json(TASKS_PATH)
    for t in tdoc.get("tasks", []):
        if t.get("taskId") == task_id:
            if target:
                t["milestone"] = target
            else:
                t.pop("milestone", None)
            t["updatedAt"] = now_iso()
            tdoc["updatedAt"] = t["updatedAt"]
            dump_json(TASKS_PATH, tdoc)
            break

    print(f"Reassigned {task_id} -> {target or 'unassigned'} in {slug}")
    if not getattr(args, "no_commit", False):
        commit_governed_state(f"task({task_id}): milestone -> {target or 'unassigned'} ({slug})")


def update_task(args):
    doc = load_json(TASKS_PATH)
    tasks = doc.get("tasks", [])
    task = next((t for t in tasks if t.get("taskId") == args.task_id), None)
    if task is None:
        raise ValueError(f"task not found: {args.task_id}")

    if task.get("revision") != args.expected_revision:
        raise ValueError(
            f"{args.task_id}: revision mismatch (expected {args.expected_revision}, found {task.get('revision')})"
        )

    patch = parse_patch(args.patch)
    validate_task_patch(args.task_id, patch)

    new_task = copy.deepcopy(task)
    new_task.update(patch)
    validate_state_transition(args.task_id, task.get("state"), new_task.get("state"))
    new_task["updatedAt"] = now_iso()
    new_task["updatedBy"] = args.actor
    new_task["revision"] = task.get("revision", 0) + 1
    # #285: createdAt is immutable once born — preserve the original even if a
    # patch tried to carry one. completedAt stamps the FIRST entry into done so
    # cycle-time (completedAt - createdAt) is computable.
    if task.get("createdAt"):
        new_task["createdAt"] = task["createdAt"]
    if new_task.get("state") == "done" and task.get("state") != "done" and not new_task.get("completedAt"):
        new_task["completedAt"] = new_task["updatedAt"]
    validate_task_shape(args.task_id, new_task)
    validate_board_fields(args.task_id, new_task, require_present=False)
    validate_done_gate(args.task_id, task.get("state"), new_task)

    if args.check:
        print(json.dumps(new_task, indent=2))
        return

    for idx, candidate in enumerate(tasks):
        if candidate.get("taskId") == args.task_id:
            tasks[idx] = new_task
            break
    doc["updatedAt"] = new_task["updatedAt"]
    dump_json(TASKS_PATH, doc)
    restamp_lease_on_transition(args.task_id, task.get("state"), new_task.get("state"))
    print(f"Updated task {args.task_id} -> revision {new_task['revision']}")

    # #447: opt-in atomic commit for important manual updates. Off by default so the
    # queue-runner's high-frequency state transitions don't generate a commit storm —
    # updates patch an EXISTING task (merge driver reconciles fields by revision), a far
    # less catastrophic loss than a vanished create. Pass --commit to make it durable now.
    if getattr(args, "commit", False):
        commit_governed_state(f"task({args.task_id}): update -> r{new_task['revision']}")


def correct_state(args):
    """Audited escape hatch for DATA CORRECTION, not workflow progress.

    The forward-only ALLOWED_STATE_TRANSITIONS graph models a task being
    *worked* — it deliberately has no rewind edges, so a task mis-created at
    the wrong state (e.g. the #098 migration dropping tasks into
    needs_verification/blocked with no matching content) cannot be fixed via
    task-update. This bypasses the transition check ON PURPOSE, but requires a
    --reason and records every correction in stateCorrections[] so the override
    is explicit and auditable rather than a silent backdoor around workflow.
    Shape + done-gate are still enforced (a correction can't fake a completion).

    --retroactive is a narrower escape hatch for closing tasks that were ALREADY
    completed before the governed system existed (e.g. #098 imported board items
    like #066 that were deployed pre-migration). Walking such a task to done
    honestly would mean fabricating an in_progress -> needs_verification workflow
    chain it never had. Mirroring create-task --backfill, --retroactive (only
    valid with --to-state done) skips the done-gate's "must come from
    needs_verification + rich artifacts" requirement, and instead records the
    --reason as the verificationMethod note. blockerOrNone/nextAction are forced
    to none. The correction is still audited in stateCorrections[].
    """
    reason = (args.reason or "").strip()
    if not reason:
        raise ValueError("correct-state requires a non-empty --reason")
    if args.to_state not in VALID_TASK_STATES:
        raise ValueError(f"{args.task_id}: invalid target state {args.to_state!r}")
    retroactive = getattr(args, "retroactive", False)
    if retroactive and args.to_state != "done":
        raise ValueError("correct-state --retroactive is only valid with --to-state done")

    doc = load_json(TASKS_PATH)
    tasks = doc.get("tasks", [])
    task = next((t for t in tasks if t.get("taskId") == args.task_id), None)
    if task is None:
        raise ValueError(f"task not found: {args.task_id}")
    if task.get("revision") != args.expected_revision:
        raise ValueError(
            f"{args.task_id}: revision mismatch (expected {args.expected_revision}, found {task.get('revision')})"
        )

    old_state = task.get("state")
    new_task = copy.deepcopy(task)
    new_task["state"] = args.to_state
    if retroactive:
        # Substitute an honest audit note for the workflow chain we're legitimately
        # skipping — the task is terminal data, not live work in flight.
        new_task["blockerOrNone"] = "none"
        new_task["nextAction"] = "none"
        if not new_task.get("verificationMethod"):
            new_task["verificationMethod"] = f"retroactive: {reason}"
        if not new_task.get("expectedArtifact"):
            new_task["expectedArtifact"] = "(retroactive — completed before governance)"
    correction = {
        "from": old_state,
        "to": args.to_state,
        "reason": reason,
        "actor": args.actor,
        "at": now_iso(),
        "retroactive": retroactive,
    }
    new_task.setdefault("stateCorrections", []).append(correction)
    new_task["updatedAt"] = correction["at"]
    new_task["updatedBy"] = args.actor
    new_task["revision"] = task.get("revision", 0) + 1
    # #285: keep completedAt honest across a correction — stamp it when a
    # correction lands a task in done (e.g. retroactive close), and clear a stale
    # one if a correction pulls a task back out of done.
    if task.get("createdAt"):
        new_task["createdAt"] = task["createdAt"]
    if args.to_state == "done":
        new_task.setdefault("completedAt", correction["at"])
    elif old_state == "done":
        new_task.pop("completedAt", None)
    # shape always applies; done-gate too unless this is an audited retroactive close
    validate_task_shape(args.task_id, new_task)
    if not retroactive:
        validate_done_gate(args.task_id, old_state, new_task)

    if args.check:
        print(json.dumps(new_task, indent=2, ensure_ascii=False))
        return

    for idx, candidate in enumerate(tasks):
        if candidate.get("taskId") == args.task_id:
            tasks[idx] = new_task
            break
    doc["updatedAt"] = new_task["updatedAt"]
    dump_json(TASKS_PATH, doc)
    restamp_lease_on_transition(args.task_id, old_state, args.to_state)
    print(f"Corrected task {args.task_id}: {old_state} -> {args.to_state} (revision {new_task['revision']})")


def dismiss_task(args):
    """Drop an untriaged suggestion (#417) — terminal 'dropped', honest by design.

    Auto-filed insight/inbox suggestions (insights-to-board.py) that triage judges
    not-worth-doing had no cull path: 'done' is hard-gated to needs_verification +
    rich artifacts, so the only way to clear them was to FABRICATE a completion that
    never happened. 'dropped' is a distinct terminal state meaning triaged-and-
    discarded — no work occurred, so no rich fields are required. Only valid from a
    pre-work state (inbox/queued); real work in flight must use blocked/failed or an
    audited correct-state, never a silent drop. Requires --reason; audited in
    stateCorrections[] like correct-state so the discard is explicit, not a backdoor.
    """
    reason = (args.reason or "").strip()
    if not reason:
        raise ValueError("dismiss requires a non-empty --reason")

    doc = load_json(TASKS_PATH)
    tasks = doc.get("tasks", [])
    task = next((t for t in tasks if t.get("taskId") == args.task_id), None)
    if task is None:
        raise ValueError(f"task not found: {args.task_id}")
    if task.get("revision") != args.expected_revision:
        raise ValueError(
            f"{args.task_id}: revision mismatch (expected {args.expected_revision}, found {task.get('revision')})"
        )
    old_state = task.get("state")
    if old_state not in DISMISSABLE_STATES:
        raise ValueError(
            f"{args.task_id}: dismiss only allowed from {sorted(DISMISSABLE_STATES)} "
            f"(state is {old_state!r}); real work in flight uses blocked/failed/correct-state"
        )

    correction = {
        "from": old_state,
        "to": "dropped",
        "reason": reason,
        "actor": args.actor,
        "at": now_iso(),
        "dismissed": True,
    }
    new_task = copy.deepcopy(task)
    new_task["state"] = "dropped"
    new_task["blockerOrNone"] = "none"
    new_task["nextAction"] = "none"
    new_task.setdefault("stateCorrections", []).append(correction)
    new_task["updatedAt"] = correction["at"]
    new_task["updatedBy"] = args.actor
    new_task["revision"] = task.get("revision", 0) + 1
    if task.get("createdAt"):
        new_task["createdAt"] = task["createdAt"]
    new_task.setdefault("droppedAt", correction["at"])
    # Shape still applies (taskId/title/etc.); the done-gate does NOT — dropped is
    # not done, and RICH_REQUIRED_STATES excludes it, so no fabricated artifacts.
    validate_task_shape(args.task_id, new_task)

    if args.check:
        print(json.dumps(new_task, indent=2, ensure_ascii=False))
        return

    for idx, candidate in enumerate(tasks):
        if candidate.get("taskId") == args.task_id:
            tasks[idx] = new_task
            break
    doc["updatedAt"] = new_task["updatedAt"]
    dump_json(TASKS_PATH, doc)
    restamp_lease_on_transition(args.task_id, old_state, "dropped")
    print(f"Dismissed task {args.task_id}: {old_state} -> dropped (revision {new_task['revision']})")


def update_live_focus(args):
    doc = load_json(FOCUS_PATH)
    if doc.get("revision") != args.expected_revision:
        raise ValueError(
            f"live-focus: revision mismatch (expected {args.expected_revision}, found {doc.get('revision')})"
        )

    patch = parse_patch(args.patch)
    validate_focus_patch(patch)

    new_doc = copy.deepcopy(doc)
    new_doc.update(patch)
    new_doc["updatedAt"] = now_iso()
    new_doc["updatedBy"] = args.actor
    new_doc["revision"] = doc.get("revision", 0) + 1

    if args.check:
        print(json.dumps(new_doc, indent=2))
        return

    dump_json(FOCUS_PATH, new_doc)
    print(f"Updated live-focus -> revision {new_doc['revision']}")


def _catchup_task_counter(task_id):
    """Keep task-counter.json monotonic vs the ids actually created (#647/I6).
    create-task accepts any unused '#NNN', so a caller that mints an id by eye
    (instead of agent-work.py alloc-id) lands a task ABOVE lastAssigned and the
    counter 'regresses' — the recurring I6 drift. After a successful create,
    catch the counter up under the same flock alloc-id uses. Best-effort: the
    governed write already landed; a counter hiccup must never fail the create."""
    try:
        import fcntl
        m = re.search(r"\d+", str(task_id) or "")
        if not m:
            return
        num = int(m.group(0))
        # Derive from TASKS_PATH, not ROOT: tests monkeypatch TASKS_PATH into a tmp
        # sandbox, and resolving the counter against ROOT wrote the CANONICAL
        # counter from those sandboxes — test_planref's fixture id #901 bumped the
        # real sequence 648->901 on 2026-07-08, burning ids 668-901 (#912, the
        # #283 split-brain class). Following the store keeps sandbox writes
        # sandboxed; in prod both files live in docs/process/state/ as before.
        counter_path = TASKS_PATH.parent / "task-counter.json"
        lock_path = counter_path.with_suffix(".json.lock")
        with lock_path.open("w") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            doc = json.loads(counter_path.read_text())
            if num > int(doc.get("lastAssigned", 0)):
                doc["lastAssigned"] = num
                doc["updatedAt"] = now_iso()
                counter_path.write_text(json.dumps(doc, indent=2) + "\n")
    except Exception:
        pass


def _next_task_id():
    """Next id WITHOUT consuming it (preview only). The atomic allocator that
    actually bumps the counter is `agent-work.py alloc-id`."""
    try:
        counter = json.loads((ROOT / "docs/process/state/task-counter.json").read_text())
        return int(counter.get("lastAssigned", 0)) + 1
    except (OSError, ValueError):
        return None


def cmd_schema(args):
    """Print the task-creation contract — required fields + every valid enum,
    read LIVE from the canonical sources — so an agent never has to grep four
    files to learn the shape. This is the on-demand (Tier 2) layer behind the
    one-screen contract in docs/process/state/README.md."""
    nxt = _next_task_id()
    schema = {
        "canonical": "docs/process/state/tasks.json (projections are rendered — never hand-edit)",
        "nextAvailableId": nxt,
        "create": {
            "requiredFields": sorted(CREATE_TASK_REQUIRED_FIELDS),
            "boardFields": list(BOARD_FIELDS),
            "richFields": {
                "fields": list(REQUIRED_RICH_FIELDS),
                "requiredWhenStateIn": sorted(RICH_REQUIRED_STATES),
            },
            "allMutableFields": sorted(TASK_MUTABLE_FIELDS),
        },
        "validValues": {
            "priority": ["P1", "P2", "P3"],
            "state": sorted(VALID_TASK_STATES),
            "origin": sorted(VALID_ORIGINS),
            "agent": sorted(VALID_AGENTS),
            "machine": sorted(VALID_MACHINES),
            "domain": sorted(VALID_DOMAINS),
            "area": sorted(load_valid_areas()),
            "project": sorted(load_valid_project_slugs()),
            "doneWhen.type": sorted(VALID_DONEWHEN_TYPES),
        },
        "stateTransitions": {k: sorted(v) for k, v in ALLOWED_STATE_TRANSITIONS.items()},
    }

    if getattr(args, "json", False):
        print(json.dumps(schema, indent=2))
        return

    print("TASK SCHEMA — canonical: docs/process/state/tasks.json (projections are rendered)")
    print()
    print("Create a task in 3 steps (or use the /add-task skill, which wraps these):")
    print("  1) python3 scripts/agent-work.py alloc-id            # atomic next id; syncs both counters")
    print("  2) python3 scripts/update-tier1-state.py create-task --actor <you> --patch '<json>'")
    print("  3) python3 scripts/render-tier1-state.py write       # refresh board + projections")
    print("  verify: python3 scripts/agent-work.py reconcile")
    if nxt is not None:
        print(f"\nNext available id: {nxt}")
    print("\nREQUIRED (create): " + ", ".join(sorted(CREATE_TASK_REQUIRED_FIELDS)))
    print("Rich fields (required once state in {}): {}".format(
        ", ".join(sorted(RICH_REQUIRED_STATES)), ", ".join(REQUIRED_RICH_FIELDS)))
    print("\nVALID VALUES")
    for k, v in schema["validValues"].items():
        print(f"  {k:<14}: {', '.join(v) if v else '(none configured)'}")
    print("\nSTATE TRANSITIONS")
    for k, v in schema["stateTransitions"].items():
        print(f"  {k:<20} -> {', '.join(v) if v else '(terminal)'}")
    print("\nCOMMON CALLS (copy-paste shapes)")
    print("  python3 scripts/agent-work.py alloc-id                                  # atomic next id")
    print("  python3 scripts/update-tier1-state.py create-task --actor claude \\")
    print("      --patch '{\"taskId\":\"#NNN\",\"title\":...,\"summary\":...,\"why\":...,\"how\":...,")
    print("               \"priority\":\"P2\",\"state\":\"queued\",\"owner\":...,\"project\":...,")
    print("               \"area\":...,\"agent\":...,\"machine\":...,\"domain\":...,\"origin\":...}'")
    print("  python3 scripts/update-tier1-state.py task-update --actor claude --task-id '#NNN' \\")
    print("      --expected-revision N --patch '{\"state\":...}'   # rich fields required entering active states")
    print("  python3 scripts/agent-work.py claim '#NNN' --agent claude   |   unclaim <claim-id>")
    print("  python3 scripts/render-tier1-state.py write              # refresh projections after batches")
    print("\nFull field definitions: ClaudeCode/skills/add-task/task-fields-reference.md")


def main():
    parser = argparse.ArgumentParser(description="Small revision-aware Tier 1 state update helper.")
    sub = parser.add_subparsers(dest="command", required=True)

    create_p = sub.add_parser("create-task", help="Create one new task object in tasks.json")
    create_p.add_argument("--actor", required=True)
    create_p.add_argument("--patch", required=True, help="JSON object for the new task")
    create_p.add_argument(
        "--check", action="store_true", help="Validate and print the new task without writing"
    )
    create_p.add_argument(
        "--backfill",
        action="store_true",
        help="Historical/migration import — skips done-gate lifecycle check AND rich-field enforcement so pre-schema tasks can be imported as-is",
    )
    create_p.add_argument(
        "--no-commit",
        action="store_true",
        help="Skip the automatic atomic commit (default commits the new task immediately so a daemon sync can't clobber it). Use when batching many creates that commit once at the end.",
    )

    proj_p = sub.add_parser("create-project", help="Create one project record in projects.json + its taxonomy domain link")
    proj_p.add_argument("--actor", required=True)
    proj_p.add_argument("--patch", required=True, help="JSON: {name, domain, priority?, doneWhen?, scope?, goal?, slug?}")
    proj_p.add_argument("--check", action="store_true", help="Validate and print without writing")
    proj_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    ms_p = sub.add_parser("create-milestone", help="Create one milestone nested in a project record")
    ms_p.add_argument("--actor", required=True)
    ms_p.add_argument("--patch", required=True, help="JSON: {projectSlug, title, doneWhen?, weight?}")
    ms_p.add_argument("--check", action="store_true", help="Validate and print without writing")
    ms_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    upproj_p = sub.add_parser("update-project", help="Patch editable fields on a project record")
    upproj_p.add_argument("--actor", required=True)
    upproj_p.add_argument("--slug", required=True)
    upproj_p.add_argument("--patch", required=True, help="JSON: any of {name, priority, doneWhen, scope, goal, status, domain}")
    upproj_p.add_argument("--check", action="store_true", help="Validate and print without writing")
    upproj_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    arproj_p = sub.add_parser("archive-project", help="Soft-remove a project (status -> archived, reversible)")
    arproj_p.add_argument("--actor", required=True)
    arproj_p.add_argument("--slug", required=True)
    arproj_p.add_argument("--check", action="store_true", help="Print without writing")
    arproj_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    delproj_p = sub.add_parser("delete-project", help="Hard-delete an EMPTY project + its taxonomy link (guarded)")
    delproj_p.add_argument("--actor", required=True)
    delproj_p.add_argument("--slug", required=True)
    delproj_p.add_argument("--check", action="store_true", help="Print without writing")
    delproj_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    upms_p = sub.add_parser("update-milestone", help="Patch editable fields on a milestone")
    upms_p.add_argument("--actor", required=True)
    upms_p.add_argument("--slug", required=True)
    upms_p.add_argument("--milestone-id", required=True)
    upms_p.add_argument("--patch", required=True, help="JSON: any of {title, doneWhen, weight, status}")
    upms_p.add_argument("--check", action="store_true", help="Validate and print without writing")
    upms_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    arms_p = sub.add_parser("archive-milestone", help="Soft-remove a milestone (status -> archived, reversible)")
    arms_p.add_argument("--actor", required=True)
    arms_p.add_argument("--slug", required=True)
    arms_p.add_argument("--milestone-id", required=True)
    arms_p.add_argument("--check", action="store_true", help="Print without writing")
    arms_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    delms_p = sub.add_parser("delete-milestone", help="Hard-delete an EMPTY milestone (guarded)")
    delms_p.add_argument("--actor", required=True)
    delms_p.add_argument("--slug", required=True)
    delms_p.add_argument("--milestone-id", required=True)
    delms_p.add_argument("--check", action="store_true", help="Print without writing")
    delms_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    reassign_p = sub.add_parser("reassign-task", help="Move a task to a different milestone (or --unassign) within its project")
    reassign_p.add_argument("--actor", required=True)
    reassign_p.add_argument("--task-id", required=True)
    reassign_p.add_argument("--project", required=True, help="Project slug the task belongs to")
    reassign_p.add_argument("--to-milestone", help="Target milestone id (M#)")
    reassign_p.add_argument("--unassign", action="store_true", help="Remove the task from all milestones")
    reassign_p.add_argument("--check", action="store_true", help="Print without writing")
    reassign_p.add_argument("--no-commit", action="store_true", help="Skip the automatic atomic commit")

    task_p = sub.add_parser("task-update", help="Patch one task object in tasks.json")
    task_p.add_argument("--task-id", required=True)
    task_p.add_argument("--expected-revision", type=int, required=True)
    task_p.add_argument("--actor", required=True)
    task_p.add_argument("--patch", required=True, help="JSON object patch string")
    task_p.add_argument(
        "--check", action="store_true", help="Validate and print the updated object without writing"
    )
    task_p.add_argument(
        "--commit",
        action="store_true",
        help="Atomically commit this update under the sync lock (off by default to avoid commit storms from high-frequency transitions; use for important manual updates)",
    )

    correct_p = sub.add_parser(
        "correct-state",
        help="AUDITED data correction — set state bypassing the forward-only transition graph (requires --reason)",
    )
    correct_p.add_argument("--task-id", required=True)
    correct_p.add_argument("--expected-revision", type=int, required=True)
    correct_p.add_argument("--actor", required=True)
    correct_p.add_argument("--to-state", required=True, help="Target state (any valid state)")
    correct_p.add_argument(
        "--reason", required=True, help="Why this is a correction, not workflow progress (audited)"
    )
    correct_p.add_argument(
        "--retroactive",
        action="store_true",
        help="Close a pre-governance/migrated task (only with --to-state done): skips the done-gate workflow-chain requirement, records --reason as the verificationMethod note",
    )
    correct_p.add_argument(
        "--check", action="store_true", help="Validate and print the corrected object without writing"
    )

    dismiss_p = sub.add_parser(
        "dismiss",
        help="Drop an untriaged inbox/queued suggestion to terminal 'dropped' (no rich fields; requires --reason; #417)",
    )
    dismiss_p.add_argument("--task-id", required=True)
    dismiss_p.add_argument("--expected-revision", type=int, required=True)
    dismiss_p.add_argument("--actor", required=True)
    dismiss_p.add_argument(
        "--reason", required=True, help="Why this suggestion is discarded (audited in stateCorrections[])"
    )
    dismiss_p.add_argument(
        "--check", action="store_true", help="Validate and print the dropped object without writing"
    )

    focus_p = sub.add_parser(
        "live-focus-update", help="Patch the live-focus object in live-focus.json"
    )
    focus_p.add_argument("--expected-revision", type=int, required=True)
    focus_p.add_argument("--actor", required=True)
    focus_p.add_argument("--patch", required=True, help="JSON object patch string")
    focus_p.add_argument(
        "--check", action="store_true", help="Validate and print the updated object without writing"
    )

    schema_p = sub.add_parser(
        "schema",
        aliases=["cheatsheet"],  # #517: the name people reach for when a gate rejects them
        help="Print the task-creation contract: required fields + valid enums (live)",
    )
    schema_p.add_argument("--json", action="store_true", help="Emit machine-readable JSON")

    args = parser.parse_args()

    if args.command == "cheatsheet":
        args.command = "schema"
    if args.command == "schema":
        cmd_schema(args)
    elif args.command == "create-task":
        with tasks_lock():
            create_task(args)
    elif args.command == "create-project":
        with tasks_lock():
            create_project(args)
    elif args.command == "create-milestone":
        with tasks_lock():
            create_milestone(args)
    elif args.command == "update-project":
        with tasks_lock():
            update_project(args)
    elif args.command == "archive-project":
        with tasks_lock():
            archive_project(args)
    elif args.command == "delete-project":
        with tasks_lock():
            delete_project(args)
    elif args.command == "update-milestone":
        with tasks_lock():
            update_milestone(args)
    elif args.command == "archive-milestone":
        with tasks_lock():
            archive_milestone(args)
    elif args.command == "delete-milestone":
        with tasks_lock():
            delete_milestone(args)
    elif args.command == "reassign-task":
        with tasks_lock():
            reassign_task(args)
    elif args.command == "task-update":
        with tasks_lock():
            update_task(args)
    elif args.command == "correct-state":
        with tasks_lock():
            correct_state(args)
    elif args.command == "dismiss":
        with tasks_lock():
            dismiss_task(args)
    elif args.command == "live-focus-update":
        update_live_focus(args)
    else:
        raise ValueError(f"unknown command: {args.command}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
